open HolKernel boolLib Parse bossLib;

val _ = new_theory "p4_exec_sem";

open p4Syntax;
open ottTheory;
open p4Theory p4_auxTheory;

(* New to executable semantics *)
Type e_ctx = “:('a ext_map # func_map # b_func_map)”;

(*********************************)
(* Expression-related shorthands *)

Definition is_v_def:
 (is_v (e_v v) = T) /\
 (is_v _ = F)
End

Definition get_v_def:
 (get_v (e_v v) = SOME v) /\
 (get_v _ = NONE)
End

Definition is_v_bool_def:
 (is_v_bool (e_v (v_bool b)) = T) /\
 (is_v_bool _ = F)
End

Definition is_v_bit_def:
 (is_v_bit (e_v (v_bit bitv)) = T) /\
 (is_v_bit _ = F)
End

(* NOTE: Error messages serialised using 32 bits *)
Definition is_v_err_def:
 (is_v_err (e_v (v_bit (bl, 32))) = T) /\
 (is_v_err _ = F)
End

Definition is_v_str_def:
 (is_v_str (e_v (v_str x)) = T) /\
 (is_v_str _ = F)
End

Definition is_var_def:
 (is_var (e_var x) = T) /\
 (is_var _ = F)
End

Definition to_bool_cast_exec_def:
 to_bool_cast_exec bitv =
  case oHD $ REVERSE $ FST bitv of
  | SOME bit => SOME $ v_bool bit
  | NONE => NONE
End

Definition unop_exec_def:
 (unop_exec unop_neg (v_bool b) = SOME (v_bool ~b))
 /\
 (unop_exec unop_compl (v_bit (bl,n)) = SOME (v_bit $ bitv_unop unop_compl (bl, n)))
 /\
 (unop_exec unop_neg_signed (v_bit (bl,n)) = SOME (v_bit $ bitv_unop unop_neg_signed (bl, n)))
  (* TODO: Sanity check removed. *)
(*
  if n > 0 /\ n <= 128 /\ LENGTH bl = n
  then SOME (v_bit (bitv_2comp bl n, n))
  else NONE)
*)
(* Maybe just this is better:
 SOME (v_bit (bitv_2comp bl $ LENGTH bl, n))
*)
 /\
 (unop_exec unop_un_plus (v_bit bitv) = SOME (v_bit bitv))
 /\
 (unop_exec unop v = NONE)
End

Definition e_exec_unop_def:
 (e_exec_unop unop (e_v v) = unop_exec unop v)
  /\
 (e_exec_unop _ _ = NONE)
End

Definition cast_exec_def:
 (cast_exec (cast_unsigned n) (v_bit bitv) = SOME (v_bit $ bitv_cast n bitv))
 /\
 (cast_exec (cast_unsigned n) (v_bool b) = SOME (v_bit $ bool_cast n b))
 /\
 (cast_exec cast_bool (v_bit bitv) = to_bool_cast_exec bitv)
 /\
 (cast_exec _ _ = NONE)
End

Definition e_exec_cast_def:
 (e_exec_cast (cast_unsigned n) (e_v v) = cast_exec (cast_unsigned n) v)
  /\
 (e_exec_cast (cast_bool) (e_v v) = cast_exec (cast_bool) v)
  /\
 (e_exec_cast _ _ = NONE)
End

(* TODO: Split binop into binop, binpred, ... to reduce copypaste? *)
Definition binop_exec_def:
 (binop_exec binop_mul (v_bit bitv1) (v_bit bitv2) =
  case bitv_binop binop_mul bitv1 bitv2 of
  | SOME bitv3 => SOME (v_bit bitv3)
  | NONE => NONE)
 /\
 (binop_exec binop_div (v_bit bitv1) (v_bit bitv2) =
  case bitv_binop binop_div bitv1 bitv2 of
  | SOME bitv3 => SOME (v_bit bitv3)
  | NONE => NONE)
 /\
 (binop_exec binop_mod (v_bit bitv1) (v_bit bitv2) =
  case bitv_binop binop_mod bitv1 bitv2 of
  | SOME bitv3 => SOME (v_bit bitv3)
  | NONE => NONE)
 /\
 (binop_exec binop_add (v_bit bitv1) (v_bit bitv2) =
  case bitv_binop binop_add bitv1 bitv2 of
  | SOME bitv3 => SOME (v_bit bitv3)
  | NONE => NONE)
 /\
 (binop_exec binop_sat_add (v_bit bitv1) (v_bit bitv2) =
  case bitv_binop binop_sat_add bitv1 bitv2 of
  | SOME bitv3 => SOME (v_bit bitv3)
  | NONE => NONE)
 /\
 (binop_exec binop_sub (v_bit bitv1) (v_bit bitv2) =
  case bitv_binop binop_sub bitv1 bitv2 of
  | SOME bitv3 => SOME (v_bit bitv3)
  | NONE => NONE)
 /\
 (binop_exec binop_sat_sub (v_bit bitv1) (v_bit bitv2) =
  case bitv_binop binop_sat_sub bitv1 bitv2 of
  | SOME bitv3 => SOME (v_bit bitv3)
  | NONE => NONE)
 /\
 (binop_exec binop_shl (v_bit bitv1) (v_bit bitv2) =
  SOME (v_bit (bitv_bl_binop shiftl bitv1 ((\(bl, n). (v2n bl, n)) bitv2))))
 /\
 (binop_exec binop_shr (v_bit (bl, n)) (v_bit (bl',n')) =
  let l = LENGTH bl in
  let m = v2n bl' in
  if m ≤ l
  then SOME $ v_bit $ (fixwidth n $ TAKE (l - m) bl, n)
  else SOME $ v_bit $ (fixwidth n [], n))
 /\
 (binop_exec binop_le (v_bit bitv1) (v_bit bitv2) =
  case bitv_binpred binop_le bitv1 bitv2 of
  | SOME b => SOME (v_bool b)
  | NONE => NONE)
 /\
 (binop_exec binop_ge (v_bit bitv1) (v_bit bitv2) =
  case bitv_binpred binop_ge bitv1 bitv2 of
  | SOME b => SOME (v_bool b)
  | NONE => NONE)
 /\
 (binop_exec binop_lt (v_bit bitv1) (v_bit bitv2) =
  case bitv_binpred binop_lt bitv1 bitv2 of
  | SOME b => SOME (v_bool b)
  | NONE => NONE)
 /\
 (binop_exec binop_gt (v_bit bitv1) (v_bit bitv2) =
  case bitv_binpred binop_gt bitv1 bitv2 of
  | SOME b => SOME (v_bool b)
  | NONE => NONE)
 /\
 (* TODO: This would generalize easily in theory, but
  * gives rise to enormously many autogenerated cases *)
 (binop_exec binop_neq (v_bit bitv1) (v_bit bitv2) =
  SOME (v_bool (bitv1 <> bitv2)))
 /\
 (binop_exec binop_neq (v_bool b1) (v_bool b2) =
  SOME (v_bool (b1 <> b2)))
 /\
 (binop_exec binop_eq (v_bit bitv1) (v_bit bitv2) =
  SOME (v_bool (bitv1 = bitv2)))
 /\
 (binop_exec binop_eq (v_bool b1) (v_bool b2) =
  SOME (v_bool (b1 = b2)))
 /\
 (* NOTE: Need to control length in the below to be sound wrt relational sem *)
 (binop_exec binop_and (v_bit (bl, n)) (v_bit (bl', n')) =
  if LENGTH bl = LENGTH bl'
  then
   SOME (v_bit (bitv_bl_binop band' (bl, n) (bl', n')))
  else NONE
 )
 /\
 (binop_exec binop_xor (v_bit bitv1) (v_bit bitv2) =
  SOME (v_bit (bitv_bl_binop bxor bitv1 bitv2)))
 /\
 (binop_exec binop_or (v_bit (bl, n)) (v_bit (bl', n')) =
  if LENGTH bl = LENGTH bl'
  then
   SOME (v_bit (bitv_bl_binop bor' (bl, n) (bl', n')))
  else NONE
  )
 /\
 (binop_exec binop v1 v2 = NONE)
End

Definition e_exec_binop_def:
 (e_exec_binop (e_v v1) binop (e_v v2) = binop_exec binop v1 v2)
  /\
 (e_exec_binop _ _ _ = NONE)
End

Definition e_exec_short_circuit_def:
 (e_exec_short_circuit (v_bool T) binop_bin_and e = SOME e)
  /\
 (e_exec_short_circuit (v_bool F) binop_bin_and e = SOME (e_v (v_bool F)))
  /\
 (e_exec_short_circuit (v_bool T) binop_bin_or e = SOME (e_v (v_bool T)))
  /\
 (e_exec_short_circuit (v_bool F) binop_bin_or e = SOME e)
  /\
 (e_exec_short_circuit _ _ _ = NONE)
End

(* Field access *)
Definition e_exec_acc_def:
 (e_exec_acc (e_acc (e_v (v_struct f_v_list)) f) =
  case FIND (\(k, v). k = f) f_v_list of
  | SOME (f, v) => SOME (e_v v)
  | NONE => NONE)
  /\
 (e_exec_acc (e_acc (e_v (v_header boolv f_v_list)) f) =
  case FIND (\(k, v). k = f) f_v_list of
  | SOME (f, v) => SOME (e_v v)
  | NONE => NONE)
  /\
 (e_exec_acc _ = NONE)
End

(* Note: according to the P4 definition, select can only be
 * performed on types represented by bools and bits in HOL4P4.
 * This explicit check allows to prove completeness of the CakeML-adjusted
 * semantics, which has some optimizations. *)
Definition pre_match_check_def:
 (pre_match_check [] = T) /\
 (pre_match_check ((x,v)::t) =
  case v of
  | v_bool _ => pre_match_check t
  | v_bit _ => pre_match_check t
  | _ => F)
End

Definition p4_match_mask_exec_def:
 p4_match_mask_exec val mask k =
  (case k of
   | v_bit (v', n') =>
    (case bitv_binop binop_and (v', n') mask of
     | SOME res =>
      (case bitv_binop binop_and val mask of
       | SOME res' => 
        (case bitv_binpred binop_eq res res' of
         | SOME bool => bool
         | NONE => F)
       | NONE => F)
     | NONE => F)
   | _ => F)
End

Definition p4_match_range_exec_def:
 p4_match_range_exec lo hi k =
  case k of
   | v_bit (v', n') =>
    (case bitv_binpred binop_ge (v', n') lo of
     | SOME T =>
      (case bitv_binpred binop_le (v', n') hi of
       | SOME T => T
       | _ => F)
     | _ => F)
   | _ => F
End

Definition match_exec_def:
 match_exec w s =
  case s of
  | s_sing w' => (w = w')
  | s_range w' w'' => p4_match_range_exec w' w'' w
  | s_mask w' w'' => p4_match_mask_exec w' w'' w
  | s_univ => T
End

Definition match_all_exec_def:
 (match_all_exec [] = T) /\
 (match_all_exec ((w, s)::t) =
   if match_exec w s
   then match_all_exec t
   else F)
End

Definition e_exec_select_def:
 (e_exec_select (e_v v) s_l_x_l x =
  case v of
  | v_struct x_v_l =>
   if pre_match_check x_v_l
   then
    (case (FIND (\ (s_list, x'). match_all_exec (ZIP(SND $ UNZIP x_v_l,s_list))) s_l_x_l) of
     | SOME (s_list, x') => SOME x'
     | NONE => SOME x)
   else NONE
  | _ => SOME x) /\
 (e_exec_select _ _ _ = NONE)
End

Definition e_exec_concat_def:
 (e_exec_concat (e_v (v_bit bitv1)) (e_v (v_bit bitv2)) =
  SOME (v_bit (bitv_concat bitv1 bitv2)))
  /\
 (e_exec_concat _ _ = NONE)
End

Definition e_exec_slice_def:
 (e_exec_slice (e_v (v_bit bitv1)) (e_v (v_bit bitv2)) (e_v (v_bit bitv3)) =
  case slice' bitv1 bitv2 bitv3 of
  | SOME bitv => SOME $ v_bit bitv
  | NONE => NONE)
  /\
 (e_exec_slice _ _ _ = NONE)
End
(* TODO: Not needed?
Definition slice_lval_exec_def:
 slice_lval_exec v e1 e2 =
  case v of
  | (v_bit (v, bl)) =>
   (case e1 of
    | (e_v (v_bit (v1, bl1))) =>
     (case e2 of
      | (e_v (v_bit (v2, bl2))) =>
       (case slice' (v, bl) (v1, bl1) (v2, bl2) of
        | SOME bitv => SOME $ v_bit bitv
        | NONE => NONE)
      | _ => NONE)
    | _ => NONE)
  | _ => NONE
End

Definition lookup_lval_exec_def:
  (lookup_lval_exec (ss:scope list) (lval_varname x) = lookup_v ss x) /\
  (lookup_lval_exec ss (lval_field lval f) =
     case lookup_lval_exec ss lval of
     | SOME v => acc_f v f
     | NONE => NONE) /\
 (lookup_lval_exec ss (lval_slice lval e1 e2) =
    case lookup_lval_exec ss lval of
     | SOME (v_bit (v, bl)) => (slice_lval_exec (v_bit (v, bl)) e1 e2)
     | _ => NONE
     ) /\
 (lookup_lval_exec ss (lval_null) = NONE ) /\
 (lookup_lval_exec ss (lval_paren lval) = lookup_lval_exec ss lval)
End
*)
Definition vl_of_el_exec_def:
 (vl_of_el_exec [] = SOME []) /\
 (vl_of_el_exec (h::t) =
   case get_v h of
    | SOME v =>
     (case vl_of_el_exec t of
      | SOME v_l => SOME (v::v_l)
      | NONE => NONE)
    | NONE => NONE)
End

(********************************)
(* Statement-related shorthands *)

Definition is_empty_def:
 (is_empty stmt_empty = T) /\
 (is_empty _ = F)
End

Definition is_empty_singleton_def:
 (is_empty_singleton [stmt_empty] = T) /\
 (is_empty_singleton _ = F)
End

Definition get_ret_v_def:
 (get_ret_v (stmt_ret (e_v v)) = SOME v) /\
 (get_ret_v (stmt_seq (stmt_ret (e_v v)) stmt) = SOME v) /\
 (get_ret_v _ = NONE)
End
(*
Definition assign_to_slice_exec_def:
 assign_to_slice_exec vb vb' ev1 ev2 =
  (case ev1 of
   | (e_v (v_bit (bl1, n1))) =>
    (case ev2 of
     | (e_v (v_bit (bl2, n2))) =>
      (case replace_bits vb vb' (v2n bl1) (v2n bl2) of
       | SOME bitv =>
        SOME $ v_bit (bitv, SND vb')
       | NONE => NONE)
     | _ => NONE)
   | _ => NONE)
End

Definition assign_exec_def:
 (assign_exec ss v (lval_varname x) =
  case find_topmost_map ss x of
  | SOME (i, sc) =>
   (case lookup_out ss x of
    | SOME str_opt =>
      SOME (LUPDATE (AUPDATE sc (x, (v, str_opt))) i ss)
    | NONE => NONE)
  | _ => NONE) /\
 (assign_exec ss v (lval_field lval f) =
  case lookup_lval' ss lval of
  | SOME (v_struct f_v_l) =>
   (case INDEX_OF f (MAP FST f_v_l) of
    | SOME i => assign_exec ss (v_struct (LUPDATE (f, v) i f_v_l)) lval
    | NONE => NONE)
  | SOME (v_header validity f_v_l) =>
   (case INDEX_OF f (MAP FST f_v_l) of
    | SOME i => assign_exec ss (v_header validity (LUPDATE (f, v) i f_v_l)) lval
    | NONE => NONE)
   | _ => NONE) /\    
 (assign_exec ss v (lval_slice lval ev1 ev2) =
  case v of
  | v_bit vb =>
   (case lookup_lval' ss lval of
    | SOME (v_bit vb') =>
     (case assign_to_slice_exec vb vb' ev1 ev2 of
      | SOME v_res => assign_exec ss v_res lval
      | _ => NONE)
    | _ => NONE)
  | _ => NONE) /\
 (assign_exec ss v lval_null = SOME ss) /\
 (assign_exec ss v (lval_paren lval) = assign_exec ss v lval)
End
*)
Definition stmt_exec_ass_def:
 (stmt_exec_ass lval (e_v v) ss =
  assign' ss v lval)
  /\
 (stmt_exec_ass _ _ _ = NONE)
End

Definition stmt_exec_init_def:
 (stmt_exec_init varn (e_v v) ss = initialise ss varn v)
End

Definition stmt_exec_trans_def:
 (stmt_exec_trans (e_v (v_str x)) = SOME (status_trans x))
  /\
 (stmt_exec_trans _ = NONE)
End

Definition stmt_exec_cond_def:
 (stmt_exec_cond (e_v (v_bool T)) =
  SOME T)
  /\
 (stmt_exec_cond (e_v (v_bool F)) =
  SOME F)
  /\
 (stmt_exec_cond _ = NONE)
End

Datatype:
 uninit =
   uninit_arb
 | uninit_zero
End

Definition uninit_bit_def:
 uninit_bit uninit =
  case uninit of
    uninit_arb => ARB
  | uninit_zero => F
End

Definition uninit_string_def:
 uninit_string uninit =
  case uninit of
    uninit_arb => ARB
  | uninit_zero => ""
End

Definition uninit_num_def:
 uninit_num uninit =
  case uninit of
    uninit_arb => ARB
  | uninit_zero => 0:num
End

(* TODO: Taken from cake_sem *)
Definition init_out_v_cake_def:
 (init_out_v_cake (v_bool boolv) = v_bool F) /\
 (init_out_v_cake (v_bit (bl, n)) = v_bit (extend F n [], n)) /\
 (init_out_v_cake (v_str x) = v_str "") /\
 (init_out_v_cake (v_struct ((x,v)::t)) = v_struct (((x, init_out_v_cake v))::(MAP (\(x',v'). (x', init_out_v_cake v')) t))) /\
 (init_out_v_cake (v_struct []) = v_struct []) /\
 (init_out_v_cake (v_header boolv ((x,v)::t)) =
   v_header F (( (x, init_out_v_cake v) )::(MAP (\(x',v'). (x', init_out_v_cake v')) t))) /\
 (init_out_v_cake (v_header boolv []) = v_header F []) /\
 (init_out_v_cake (v_ext_ref i) = v_ext_ref i) /\
 (init_out_v_cake v_bot = v_bot)
Termination
 WF_REL_TAC ‘measure v_size’ \\
 gs[v_size_def] \\
 rpt strip_tac \\
 ‘v_size v' < v1_size t’ suffices_by (
  gs[]
 ) \\
 metis_tac[v1_size_mem]
End

Definition init_out_v_gen_def:
  (init_out_v_gen uninit (v_bool boolv) = v_bool (uninit_bit uninit)) /\
  (init_out_v_gen uninit (v_bit (bl, n)) = v_bit (extend (uninit_bit uninit) n [], n)) /\
  (init_out_v_gen uninit (v_str x) = v_str (uninit_string uninit)) /\
  (init_out_v_gen uninit (v_struct ((x,v)::t)) = v_struct (((x, init_out_v_gen uninit v))::(MAP (\(x',v'). (x', init_out_v_gen uninit v')) t))) /\
  (init_out_v_gen uninit (v_struct []) = v_struct []) /\
  (init_out_v_gen uninit (v_header boolv ((x,v)::t)) =
    v_header F (( (x, init_out_v_gen uninit v) )::(MAP (\(x',v'). (x', init_out_v_gen uninit v')) t))) /\
  (init_out_v_gen uninit (v_header boolv []) = v_header F []) /\
  (init_out_v_gen uninit (v_ext_ref i) = v_ext_ref i) /\
  (init_out_v_gen uninit v_bot = v_bot)
Termination
 WF_REL_TAC `measure (\ (a,b). v_size b)`
End

(* TODO: uninit *)
Definition one_arg_val_for_newscope_exec_def:
 one_arg_val_for_newscope_exec d e ss =
  if is_d_out d
  then
   (case get_lval_of_e e of
    | SOME lval =>
     (case lookup_lval' ss lval of
      | SOME v =>
       if is_d_in d
       then SOME (v, SOME lval)
       else SOME (init_out_v_cake v, SOME lval)
      | NONE => NONE)
    | NONE => NONE)
  else
   (case v_of_e e of
    | SOME v => SOME (v, NONE)
    | NONE => NONE)
End

(* TODO: uninit *)
Definition update_arg_for_newscope_exec_def:
 update_arg_for_newscope_exec ss f_opt (d, x, e) =
  case f_opt of
  | SOME f =>
   (case one_arg_val_for_newscope_exec d e ss of
    | SOME (v, lval_opt) => SOME (p4$AUPDATE f (varn_name x, (v, lval_opt)))
    | NONE => NONE)
  | NONE => NONE
End

(* TODO: uninit *)
Definition all_arg_update_for_newscope_exec_def:
 all_arg_update_for_newscope_exec xlist dlist elist ss = 
  FOLDL (update_arg_for_newscope_exec ss) (SOME []) (ZIP (dlist, ZIP(xlist, elist)))
End

(* TODO: uninit *)
Definition copyin_exec_def:
 copyin_exec xlist dlist elist gsl ss_curr = 
  all_arg_update_for_newscope_exec xlist dlist elist (ss_curr++gsl)
End

Definition e_state_size_def:
(*
 (e_state_size (uninit, (e_ctx:'a e_ctx), (g_scope_list:g_scope_list), (scope_list:scope_list), (e:e)) = e_size e)
*)
 (e_state_size ((e_ctx:'a e_ctx), (g_scope_list:g_scope_list), (scope_list:scope_list), (e:e)) = e_size e)
End

(* TODO: Write explicit NONE-reducing clauses for operands of wrong types?
 *       This would reduce warnings *)
(* TODO: Use let-statements to avoid duplicate "MAP FST", et cetera *)
(* Defn.tgoal (Hol_defn "e_exec" ` *)
Definition e_exec_def:
 (********************)
 (* Variable look-up *)
 (e_exec (e_ctx:'a e_ctx) (g_scope_list:g_scope_list) (scope_list:scope_list) (e_var x) =
  case lookup_vexp2 scope_list g_scope_list x of
  | SOME v => SOME (e_v v, [])
  | NONE => NONE)
  /\
 (******************************)
 (* Struct/header field access *)
 (e_exec e_ctx g_scope_list scope_list (e_acc e_v_struct x) =
  if is_v e_v_struct
  then
   (case e_exec_acc (e_acc e_v_struct x) of
    | SOME v => SOME (v, [])
    | NONE => NONE)
   else
    (case e_exec e_ctx g_scope_list scope_list e_v_struct of
     | SOME (e_v_struct', frame_list) =>
      SOME (e_acc e_v_struct' x, frame_list)
     | NONE => NONE))
  /\
 (*********************************)
 (* Struct/header field reduction *)
 (e_exec e_ctx g_scope_list scope_list (e_struct x_e_l) =
  case unred_mem_index (MAP SND x_e_l) of
  | SOME i =>
   (* TODO: Uses oEL, but precondition for EL should be provable *)
   (case oEL i (MAP SND x_e_l) of
    | SOME x_e =>
     (case e_exec e_ctx g_scope_list scope_list x_e of
      | SOME (e', frame_list) => SOME (e_struct (ZIP (MAP FST x_e_l, (LUPDATE e' i (MAP SND x_e_l)))), frame_list)
      | NONE => NONE)
    | NONE => NONE)
  | NONE =>
   (case vl_of_el_exec (MAP SND x_e_l) of
    | SOME v_l => SOME (e_v (v_struct (ZIP (MAP FST x_e_l, v_l))), [])
    | NONE => NONE))
  /\
 (************************)
 (* Function/extern call *)
 (e_exec (ext_map, func_map, b_func_map) g_scope_list scope_list (e_call funn e_l) =
  (case lookup_funn_sig_body funn func_map b_func_map ext_map of
    | SOME (stmt, x_d_l) =>
     if LENGTH x_d_l = LENGTH e_l
     then
      (case unred_arg_index (MAP SND x_d_l) e_l of
       | SOME i =>
        (* TODO: Uses oEL, but precondition for EL should be provable *)
        (case oEL i e_l of
         | SOME elem =>
          (case e_exec (ext_map, func_map, b_func_map) g_scope_list scope_list elem of
           | SOME (e', frame_list) => SOME (e_call funn (LUPDATE e' i e_l), frame_list)
           | NONE => NONE)
         | NONE => NONE)
       | NONE =>
        (case copyin_exec (MAP FST x_d_l) (MAP SND x_d_l) e_l g_scope_list scope_list of
         | SOME scope => 
          SOME (e_var (varn_star funn), [(funn, [stmt], [scope])])
         | NONE => NONE))
     else NONE
    | NONE => NONE))
  /\
 (********)
 (* Cast *)
 (e_exec e_ctx g_scope_list scope_list (e_cast cast e) =
  if is_v e
  then
   (case e_exec_cast cast e of
    | SOME v => SOME (e_v v, [])
    | NONE => NONE)
  else
   (case e_exec e_ctx g_scope_list scope_list e of
    | SOME (e', frame_list) => SOME (e_cast cast e', frame_list)
    | NONE => NONE))
  /\
 (********************)
 (* Unary arithmetic *)
 (e_exec e_ctx g_scope_list scope_list (e_unop unop e) =
  if is_v e
  then 
   (case e_exec_unop unop e of
    | SOME v => SOME (e_v v, [])
    | NONE => NONE)
  else
   (case e_exec e_ctx g_scope_list scope_list e of
    | SOME (e', frame_list) => SOME (e_unop unop e', frame_list)
    | NONE => NONE))
  /\
 (*********************)
 (* Binary arithmetic *)
 (e_exec e_ctx g_scope_list scope_list (e_binop e1 binop e2) =
  (case e1 of
   | (e_v v) =>
    if is_short_circuitable binop
    then
     (case e_exec_short_circuit v binop e2 of
      | SOME e' => SOME (e', [])
      | NONE => NONE)
    else if is_v e2
    then
     (case e_exec_binop e1 binop e2 of
      | SOME v' => SOME (e_v v', [])
      | NONE => NONE)
    else
     (case e_exec e_ctx g_scope_list scope_list e2 of
      | SOME (e2', frame_list) => SOME (e_binop e1 binop e2', frame_list)
      | NONE => NONE)
   | _ =>
    (case e_exec e_ctx g_scope_list scope_list e1 of
     | SOME (e1', frame_list) => SOME (e_binop e1' binop e2, frame_list)
     | NONE => NONE)))
  /\
 (**********)
 (* Select *)
 (e_exec e_ctx g_scope_list scope_list (e_select e s_l_x_l x) =
  if is_v e
  then
   (case e_exec_select e s_l_x_l x of
    | SOME x' => SOME (e_v (v_str x'), [])
    | NONE => NONE)
  else
   (case e_exec e_ctx g_scope_list scope_list e of
    | SOME (e', frame_list) => SOME (e_select e' s_l_x_l x, frame_list)
    | NONE => NONE))
  /\
 (*****************)
 (* Concatenation *)
 (e_exec e_ctx g_scope_list scope_list (e_concat e1 e2) =
  if is_v_bit e1
  then 
   (if is_v_bit e2
    then 
     (case e_exec_concat e1 e2 of
      | SOME v => SOME (e_v v, [])
      | NONE => NONE)
    else
     (case e_exec e_ctx g_scope_list scope_list e2 of
      | SOME (e2', frame_list) => SOME (e_concat e1 e2', frame_list)
      | NONE => NONE))
  else
   (case e_exec e_ctx g_scope_list scope_list e1 of
    | SOME (e1', frame_list) => SOME (e_concat e1' e2, frame_list)
    | NONE => NONE))
  /\
 (***********)
 (* Slicing *)
 (e_exec e_ctx g_scope_list scope_list (e_slice e1 e2 e3) =
  if (is_v_bit e2 /\ is_v_bit e3)
  then
   (if is_v_bit e1
    then 
     (case e_exec_slice e1 e2 e3 of
      | SOME v => SOME (e_v v, [])
      | NONE => NONE)
    else
     (case e_exec e_ctx g_scope_list scope_list e1 of
      | SOME (e1', frame_list) => SOME (e_slice e1' e2 e3, frame_list)
      | NONE => NONE))
   else NONE)
  /\
 (e_exec _ _ _ _ = NONE)
Termination
WF_REL_TAC `measure e_state_size` >>
fs [e_state_size_def, e_size_def] >>
REPEAT STRIP_TAC >| [
  IMP_RES_TAC unred_arg_index_in_range >>
  gs[listTheory.oEL_EQ_EL] >>
  IMP_RES_TAC rich_listTheory.EL_MEM >>
  IMP_RES_TAC e3_size_mem >>
  gs[],

  IMP_RES_TAC unred_mem_index_in_range >>
  gs[listTheory.oEL_EQ_EL] >>
  IMP_RES_TAC rich_listTheory.EL_MEM >>
  `e_size (EL i (MAP SND x_e_l)) < e1_size x_e_l` suffices_by (
   fs []
  ) >>
  `e2_size (EL i (MAP FST x_e_l), EL i (MAP SND x_e_l)) < e1_size x_e_l` suffices_by (
   rpt strip_tac >>
   irule arithmeticTheory.LESS_TRANS >>
   qexists_tac `e2_size (EL i (MAP FST x_e_l),EL i (MAP SND x_e_l))` >>
   fs [e_e2_size_less]
  ) >>
  subgoal `MEM (EL i x_e_l) x_e_l` >- (
   irule rich_listTheory.EL_MEM >>
   fs [listTheory.LENGTH_MAP]
  ) >>
  imp_res_tac e1_size_mem >>
  metis_tac [EL_pair_list, listTheory.LENGTH_MAP]
]
End

(*
val e_exec_ind = tryfind (uncurry DB.fetch) [("scratch", "e_exec_ind"),
                                             ("p4_exec_sem", "e_exec_ind")];
val _ = save_thm("e_exec_ind", e_exec_ind);
*)

(*
val measure_stmt_state_size_def = Define `
 (measure_stmt_state_size ((ctx:ctx), (g_scope_list:g_scope_list), (frame_list:frame_list), (ctrl:ctrl), (status:status))
                          ((ctx':ctx), (g_scope_list':g_scope_list), (frame_list':frame_list), (ctrl':ctrl), (status':status)) =
  if LENGTH frame_list <> LENGTH frame_list'
  then LENGTH frame_list < LENGTH frame_list'
  else if LENGTH (FST $ SND $ HD frame_list) <> LENGTH (FST $ SND $ HD frame_list')
  then LENGTH (FST $ SND $ HD frame_list) < LENGTH (FST $ SND $ HD frame_list')
  else (stmt_size (HD $ FST $ SND $ HD frame_list) < stmt_size (HD $ FST $ SND $ HD frame_list')))
`;
*)

Definition is_consts_exec_def:
 (is_consts_exec [] = T) /\
 (is_consts_exec (h::t) = ((is_const h) /\ (is_consts_exec t)))
End

Theorem vl_of_el_MAP_e_v:
!el.
is_consts_exec el ==>
el = MAP e_v (vl_of_el el)
Proof
Induct_on `el` >- (
 fs [is_consts_exec_def, vl_of_el_def]
) >>
rpt strip_tac >>
fs [is_consts_exec_def, vl_of_el_def] >>
Cases_on `h` >> (
 fs [is_const_def]
) >>
fs [v_of_e_def]
QED

Definition separate_exec_def:
 separate_exec scope_list =
  let i = LENGTH scope_list in
  if i >= 2
  then
   SOME (DROP (i − 2) scope_list, TAKE (i − 2) scope_list)
  else NONE
End

(* arb_from_tau, generalised for different (un)initialisation schemes *)
Definition arb_from_tau_gen_def:
 (arb_from_tau_gen uninit tau_bool        = v_bool $ uninit_bit uninit) /\
 (arb_from_tau_gen uninit (tau_bit width) = v_bit (REPLICATE width (uninit_bit uninit), width)) /\
 (arb_from_tau_gen uninit tau_bot         = v_bot) /\
 (arb_from_tau_gen uninit tau_ext         = v_ext_ref $ uninit_num uninit) /\
 (arb_from_tau_gen uninit (tau_xtl struct_ty_struct xtl) =  
  v_struct (MAP (λ(x,t). (x, arb_from_tau_gen uninit t)) xtl)) /\
 (arb_from_tau_gen uninit (tau_xtl struct_ty_header xtl) =
  v_header (uninit_bit uninit) (MAP (λ(x,t). (x, arb_from_tau_gen uninit t)) xtl))
End

Definition declare_list_in_fresh_scope_exec_def:
 declare_list_in_fresh_scope_exec uninit (t_scope:t_scope) =
  MAP (\(x, (t, lvalop)). (x, (arb_from_tau_gen uninit t, NONE))) t_scope
End

(* TODO: From cake_sem *)
(* TODO: This looks dumber than arb_from_tau_gen, try to replace this entirely *)
(* TODO: Rename, should be no clash with cake_sem formulation *)
Definition init_v_from_tau_cake_def:
 (init_v_from_tau_cake tau_bool = v_bool F) /\
 (init_v_from_tau_cake (tau_bit w) = v_bit (GENLIST (\x. F) w, w)) /\
 (init_v_from_tau_cake tau_bot = v_bot) /\
 (init_v_from_tau_cake tau_ext = v_ext_ref 0) /\
 (init_v_from_tau_cake (tau_xtl struct_ty_struct []) = v_struct []) /\
 (init_v_from_tau_cake (tau_xtl struct_ty_struct ((x0,t0)::xtl)) =
  v_struct ((x0, init_v_from_tau_cake t0)::(MAP (\(x,t). (x, init_v_from_tau_cake t)) xtl))) /\
 (init_v_from_tau_cake (tau_xtl struct_ty_header [] ) = v_header F [] ) /\
 (init_v_from_tau_cake (tau_xtl struct_ty_header ((x0,t0)::xtl)) =
   v_header F ((x0, init_v_from_tau_cake t0)::(MAP (\(x,t). (x, init_v_from_tau_cake t)) xtl)))
Termination
WF_REL_TAC `measure tau_size`
End
(* TODO: Hard-coded to zeroes *)
Definition declare_list_in_fresh_scope_exec'_def:
 declare_list_in_fresh_scope_exec' (t_scope:t_scope) =
  MAP (\(x, (t, lvalop)). (x, (init_v_from_tau_cake t, NONE))) t_scope
End

Theorem arb_from_tau_gen_arb_equiv:
!tau.
arb_from_tau_gen uninit_arb tau = arb_from_tau tau
Proof
‘(!tau. (\tau. arb_from_tau_gen uninit_arb tau = arb_from_tau tau) tau) /\
 (!l:(string # tau) list. (\xtl. EVERY (\tau. arb_from_tau_gen uninit_arb tau = arb_from_tau tau) $ MAP SND xtl) l) /\
 !p:(string # tau). (\xt. arb_from_tau_gen uninit_arb $ SND xt = arb_from_tau $ SND xt) p’ suffices_by gs[] >>
irule tau_induction >> (
 gs[arb_from_tau_gen_def, arb_from_tau_def, uninit_bit_def, uninit_string_def, uninit_num_def]
) >>
rpt strip_tac >- (
 Cases_on ‘s’ >> (
  gs[arb_from_tau_gen_def, arb_from_tau_def]
 ) >> (
  (* TODO: Because of the arb_from_tau definition... *)
  Cases_on ‘l’ >> (
   gs[arb_from_tau_def, uninit_bit_def]
  ) >>
  PairCases_on ‘h’ >>
  gs[arb_from_tau_def, listTheory.EVERY_MAP, uninit_bit_def] >>
  irule listTheory.MAP_CONG >>
  simp[] >>
  rpt strip_tac >>
  Cases_on ‘x’ >>
  simp[] >>
  fs[listTheory.EVERY_MEM] >>
  qpat_x_assum ‘!x. _’ (fn thm => irule $ SIMP_RULE std_ss [] $ Q.SPECL [‘(q,r)’] thm) >>
  metis_tac[]
 )
) >>
gs[rich_listTheory.REPLICATE_GENLIST] >>
irule listTheory.GENLIST_CONG >>
simp[combinTheory.K_THM]
QED

Theorem declare_list_in_fresh_scope_exec_arb_equiv:
!decl_list.
declare_list_in_fresh_scope_exec uninit_arb decl_list =
 declare_list_in_fresh_scope decl_list
Proof
Induct >> (
 gs[declare_list_in_fresh_scope_exec_def, declare_list_in_fresh_scope_def]
) >>
rpt strip_tac >>
PairCases_on ‘h’ >>
gs[arb_from_tau_gen_arb_equiv]
QED

Definition get_e_ctx_def:
 get_e_ctx ((apply_table_f, ext_map, func_map, b_func_map, pars_map, tbl_map):'a ctx) = (ext_map, func_map, b_func_map)
End

(* TODO: Check for funn agreement? *)
Definition stmt_exec_seq_finish_def:
 (stmt_exec_seq_finish (ascope':'a, g_scope_list':g_scope_list, frame_list':frame list, status':status) (funn:funn) stmt2 =
  case frame_list' of
  | [(funn, [stmt1'], scope_list')] =>
   (case status' of 
    | status_running =>
     SOME (ascope', g_scope_list', [(funn, [stmt_seq stmt1' stmt2], scope_list')], status_running)
    | _ =>
     SOME (ascope', g_scope_list', [(funn, [stmt1'], scope_list')], status'))     
  | [(funn, stmt1''::[stmt1'], scope_list')] =>
   SOME (ascope', g_scope_list', [(funn, [stmt1'']++[stmt_seq stmt1' stmt2], scope_list')], status_running)
  | (frame::[(funn, [stmt1'], scope_list')]) =>
   SOME (ascope', g_scope_list', (frame::[(funn, [stmt_seq stmt1' stmt2], scope_list')]), status_running)
  | _ => NONE
 )
End

Definition stmt_exec_stack_finish_def:
 (stmt_exec_stack_finish (ascope':'a, g_scope_list':g_scope_list, frame_list':frame list, status':status) (funn:funn) stmt_stack (scope_list:scope list) =
  case frame_list' of
   (* Regular case *)
   | [(funn, [stmt'], scope_list')] =>
    SOME (ascope', g_scope_list', [(funn, stmt'::stmt_stack, scope_list')], status')
   (* Block entry *)
   | [(funn, stmt''::[stmt'], scope_list')] =>
    SOME (ascope', g_scope_list', [(funn, stmt''::(stmt'::stmt_stack), scope_list')], status')
   (* Function call *)
   | ((funn', [stmt'], scope_list')::[(funn, [stmt''], scope_list)]) =>
    SOME (ascope', g_scope_list', ((funn', [stmt'], scope_list')::[(funn, stmt''::stmt_stack, scope_list)]), status')
   (* TODO: What can happen here? *)
   | _ => NONE
 )
End

Definition stmt_exec_def:
 (******************************************)
 (* Catch-all clauses for special statuses *)
 (stmt_exec (ctx:'a ctx) ((ascope:'a, g_scope_list:g_scope_list, frame_list:frame_list, (status_returnv v):status)) = NONE)
  /\
 (stmt_exec _ (_, _, _, status_trans x) = NONE)
  /\
 (* Empty frame list *)
 (stmt_exec _ (_, _, [], _) = NONE)
  /\
 (* Empty scope stack *)
 (stmt_exec _ (_, _, [(funn, stmt_stack, [])], _) = NONE)
  /\
 (**************)
 (* Assignment *)
 (stmt_exec ctx (ascope, g_scope_list, [(funn, [stmt_ass lval e], scope_list)], status_running) =
  if is_v e
  then
   (* TODO: Put separate_exec in stmt_exec_ass? *)
   (case stmt_exec_ass lval e (scope_list++g_scope_list) of
    | SOME scope_list'' =>
     (case separate_exec scope_list'' of
      | SOME (g_scope_list', scope_list') =>
       SOME (ascope, g_scope_list', [(funn, [stmt_empty], scope_list')], status_running)
      | _ => NONE)
    | NONE => NONE)
  else
   (case e_exec (get_e_ctx ctx) g_scope_list scope_list e of
    | SOME (e', frame_list) =>
     SOME (ascope, g_scope_list, frame_list++[(funn, [stmt_ass lval e'], scope_list)], status_running)
    | _ => NONE))
  /\
 (**************)
 (* Transition *)
 (* +5s *)
 (stmt_exec ctx (ascope, g_scope_list, [(funn, [stmt_trans e], scope_list)], status_running) =
  if is_v e
  then
   (case stmt_exec_trans e of
    | SOME status' => SOME (ascope, g_scope_list, [(funn, [stmt_empty], scope_list)], status')
    | NONE => NONE)
  else
   (case e_exec (get_e_ctx ctx) g_scope_list scope_list e of
    | SOME (e', frame_list) =>
     SOME (ascope, g_scope_list, frame_list++[(funn, [stmt_trans e'], scope_list)], status_running)
    | NONE => NONE))
  /\
 (***************)
 (* Conditional *)
 (* +5s *)
 (stmt_exec ctx (ascope, g_scope_list, [(funn, [stmt_cond e stmt1 stmt2], scope_list)], status_running) =
  (* TODO: Make this more efficient by using a single get_v_bool e *)
  if is_v_bool e
  then
   (case stmt_exec_cond e of
    | SOME T => SOME (ascope, g_scope_list, [(funn, [stmt1], scope_list)], status_running)
    | SOME F => SOME (ascope, g_scope_list, [(funn, [stmt2], scope_list)], status_running)
    | NONE => NONE)
  else
   (case e_exec (get_e_ctx ctx) g_scope_list scope_list e of
    | SOME (e', frame_list) =>
     SOME (ascope, g_scope_list, frame_list++[(funn, [stmt_cond e' stmt1 stmt2], scope_list)], status_running)
    | NONE => NONE))
  /\
 (*********************)
 (* Table application *)
 (* +9s *)
 (stmt_exec (apply_table_f, ext_map, func_map, b_func_map, pars_map, tbl_map) (ascope, g_scope_list, [(funn, [stmt_app t_name e_l], scope_list)], status_running) =
  (* TODO: Merge index_not_const and oEL? *)
  (case index_not_const e_l of
   | SOME i =>
    (case oEL i e_l of
     | SOME elem =>
      (case e_exec (ext_map, func_map, b_func_map) g_scope_list scope_list elem of
       | SOME (e', frame_list) =>
        SOME (ascope, g_scope_list, frame_list++[(funn, [stmt_app t_name (LUPDATE e' i e_l)], scope_list)], status_running)
       | NONE => NONE)
     | NONE => NONE)
   | NONE =>
    (case ALOOKUP tbl_map t_name of
     | SOME (mk_l, (default_f, default_f_args)) =>
      (if LENGTH mk_l = LENGTH e_l
       then
        (case apply_table_f (t_name, e_l, mk_l, (default_f, default_f_args), ascope) of
         | SOME (f, f_args) =>
          (* TODO: This has been relaxed to allow non-constant function arguments *)
          SOME (ascope, g_scope_list, [(funn, [stmt_ass lval_null (e_call (funn_name f) f_args)], scope_list)], status_running)
         | NONE => NONE)
       else NONE)
     | NONE => NONE)))
  /\
 (**********)
 (* Return *)
 (* +5s *)
 (stmt_exec ctx (ascope, g_scope_list, [(funn, [stmt_ret e], scope_list)], status_running) =
  (case get_v e of
   | SOME v => SOME (ascope, g_scope_list, [(funn, [stmt_empty], scope_list)], status_returnv v)
   | NONE => 
    (case e_exec (get_e_ctx ctx) g_scope_list scope_list e of
     | SOME (e', frame_list) =>
      SOME (ascope, g_scope_list, frame_list++[(funn, [stmt_ret e'], scope_list)], status_running)
     | NONE => NONE)))
  /\
 (**********)
 (* Extern *)
 (* +5s *)
 (stmt_exec (apply_table_f, ext_map, func_map, b_func_map, pars_map, tbl_map) (ascope, g_scope_list, [(funn, [stmt_ext], scope_list)], status_running) =
  (* TODO: Put ext fun execution inside lookup_ext_fun (and rename?) *)
  (case lookup_ext_fun funn ext_map of
   | SOME ext_fun =>
    (case ext_fun (ascope, g_scope_list, scope_list) of
     | SOME (ascope', scope_list', status') =>
      SOME (ascope', g_scope_list, [(funn, [stmt_empty], scope_list')], status')
     | NONE => NONE)
   | NONE => NONE))
  /\
 (*********)
 (* Block *)
 (* -5s??? *)
 (stmt_exec ctx (ascope, g_scope_list, [(funn, [stmt_block decl_list stmt], scope_list)], status_running) =
   SOME (ascope, g_scope_list, [(funn, [stmt]++[stmt_empty], ((declare_list_in_fresh_scope_exec' decl_list)::scope_list))], status_running))
  /\
 (************)
 (* Sequence *)
 (* +13s/+9s *)
 (stmt_exec ctx (ascope, g_scope_list, [(funn, [stmt_seq stmt1 stmt2], scope_list)], status_running) =
  if is_empty stmt1
  then SOME (ascope, g_scope_list, [(funn, [stmt2], scope_list)], status_running)
  else
   (* Note: this only allows for 0 or 1 frame being added, or (exclusively) 1 stmt element *)
   (case stmt_exec ctx (ascope, g_scope_list, [(funn, [stmt1], scope_list)], status_running) of
    | SOME state' => stmt_exec_seq_finish state' funn stmt2
(* TODO: Replaced by definition - is there any improvement in extraction time?
    | SOME (ascope', g_scope_list', [(funn, [stmt1'], scope_list')], status') =>
     (case status' of 
      | status_running =>
       SOME (ascope', g_scope_list', [(funn, [stmt_seq stmt1' stmt2], scope_list')], status_running)
      | _ =>
       SOME (ascope', g_scope_list', [(funn, [stmt1'], scope_list')], status'))
    | SOME (ascope', g_scope_list', [(funn, stmt1''::[stmt1'], scope_list')], status_running) =>
     SOME (ascope', g_scope_list', [(funn, [stmt1'']++[stmt_seq stmt1' stmt2], scope_list')], status_running)
    | SOME (ascope', g_scope_list', (frame::[(funn, [stmt1'], scope_list')]), status_running) =>
     SOME (ascope', g_scope_list', (frame::[(funn, [stmt_seq stmt1' stmt2], scope_list')]), status_running)
*)
    | _ => NONE)
 )
  /\
 (stmt_exec ctx (ascope, g_scope_list, [(funn, [stmt_empty], scope_list)], status_running) = NONE)
 /\
 (*********************)
 (* Stmt stack clause *)
 (*********************)
 (* TODO: Should the case statement be handled by better matching in the clause? *)
 (stmt_exec ctx (ascope, g_scope_list, [(funn, stmt::stmt_stack, scope_list)], status) =
  if is_empty stmt
  then
   (case stmt_stack of
    | [] => NONE
    | _ =>
     (case scope_list of
      | [] => NONE
      | (h_scope::scope_list') => SOME (ascope, g_scope_list, [(funn, stmt_stack, scope_list')], status)))
  else
   (case stmt_exec ctx (ascope, g_scope_list, [(funn, [stmt], scope_list)], status) of
   | SOME state' =>
    stmt_exec_stack_finish state' funn stmt_stack scope_list
(* TODO: Replaced by definition - is there any improvement in extraction time?
    (case frame_list' of
     (* Regular case *)
     | [(funn, [stmt'], scope_list')] =>
      SOME (ascope', g_scope_list', [(funn, stmt'::stmt_stack, scope_list')], status')
     (* Block entry *)
     | [(funn, stmt''::[stmt'], scope_list')] =>
      SOME (ascope', g_scope_list', [(funn, stmt''::(stmt'::stmt_stack), scope_list')], status')
     (* Function call *)
     | ((funn', [stmt'], scope_list')::[(funn, [stmt''], scope_list)]) =>
      SOME (ascope', g_scope_list', ((funn', [stmt'], scope_list')::[(funn, stmt''::stmt_stack, scope_list)]), status')
     (* TODO: What can happen here? *)
     | _ => NONE)
*)
   | NONE => NONE)
 )
  /\
 (stmt_exec _ _ = NONE)
Termination
 WF_REL_TAC ‘measure (\ (ctx, ascope, g_scope_list, frame, status).
  (case frame of
   | [(funn,stmt_stack,scopes)] => FOLDR (\stmt n. stmt_size stmt + n + 1) 0 stmt_stack
   | _ => 0))’ >>
  gs[is_empty_def]
End


Theorem exec_stmt_SOME_init_running:
!ctx ascope ascope' g_scope_list g_scope_list' funn stmt frame_list' scope_list status status'.
stmt_exec ctx (ascope, g_scope_list, [(funn, [stmt], scope_list)], status) =
        SOME (ascope', g_scope_list', frame_list', status') ==>
 status = status_running
Proof
rpt strip_tac >>
Cases_on `stmt` >> (
 fs []
) >> (
 Cases_on `status` >> (
  fs [stmt_exec_def]
 )
)
QED

Theorem e_exec_new_frame:
!ctx g_scope_list scope_list e e' frame_list'.
e_exec ctx g_scope_list scope_list e = SOME (e',frame_list') ==>
(frame_list' = [] \/
 ?funn stmt scope. frame_list' = [(funn, [stmt], [scope])])
Proof
‘!ctx g_scope_list scope_list e.
 (\ctx' g_scope_list' scope_list' e'.
  !e'' frame_list''.
  e_exec ctx' g_scope_list' scope_list' e' = SOME (e'', frame_list'') ==>
  (frame_list'' = [] \/
   ?funn'' stmt'' scope''. frame_list'' = [(funn'', [stmt''], [scope''])])
 ) ctx g_scope_list scope_list e’ suffices_by (
 metis_tac []
) >>
irule e_exec_ind >>
fs [e_exec_def] >>
rpt strip_tac >| [
 gvs[AllCaseEqs()],

 (* Unop *)
 gvs[AllCaseEqs()],

 (* TODO: Weird blob goal... *)
 Cases_on `e1` >> (
  fs [e_exec_def]
 ) >> (gvs[AllCaseEqs()]),

 (* Slicing *)
 gvs[AllCaseEqs()],

 (* Concatenation *)
 gvs[AllCaseEqs()],

 (* Access *)
  gvs[AllCaseEqs()],

 (* Select *)
 gvs[AllCaseEqs()],

 (* Struct *)
 gvs[AllCaseEqs()],

 (* Unop *)
 gvs[AllCaseEqs()],

 (* Variable lookup *)
 gvs[AllCaseEqs()]
]
QED

Theorem exec_stmt_ass_SOME_REWRS:
!apply_table_f ext_map func_map b_func_map pars_map tbl_map ascope ascope' g_scope_list g_scope_list' funn lval e stmt_stack frame_list' scope_list status'.
stmt_exec (apply_table_f,ext_map,func_map,b_func_map,pars_map,tbl_map) (ascope, g_scope_list, [(funn, (stmt_ass lval e)::stmt_stack, scope_list)], status_running) =
        SOME (ascope', g_scope_list', frame_list', status') <=>
 (is_v e ==>
  ?scope_list'' scope_list'.
   (stmt_exec_ass lval e (scope_list++g_scope_list) = SOME scope_list'') /\
   (separate_exec scope_list'' = SOME (g_scope_list', scope_list')) /\
   (frame_list' = [(funn, (stmt_empty)::stmt_stack, scope_list')])) /\
 (~is_v e ==>
  ?e' frame_list''.
   (e_exec (ext_map,func_map,b_func_map) g_scope_list scope_list e = SOME (e', frame_list'')) /\
   (g_scope_list' = g_scope_list) /\
   (frame_list' = (frame_list''++[(funn, (stmt_ass lval e')::stmt_stack, scope_list)]))) /\
 scope_list <> [] /\
 ascope' = ascope /\
 status' = status_running
Proof
rpt strip_tac >>
Cases_on `scope_list` >> Cases_on `stmt_stack` >> (
 gs[stmt_exec_def]
) >>
Cases_on `is_v e` >> (
 gvs[AllCaseEqs()]
) >| [
 Cases_on `stmt_exec_ass lval e ((h::t) ++ g_scope_list)` >> (
  fs []
 ) >>
 Cases_on `separate_exec x` >> (
  gs[]
 ) >>
 PairCases_on ‘x'’ >>
 gvs[AllCaseEqs()] >>
 metis_tac [],

 Cases_on `e_exec (ext_map,func_map,b_func_map) g_scope_list (h::t) e` >> (
  fs [get_e_ctx_def]
 ) >>
 PairCases_on `x` >>
 fs [get_e_ctx_def] >>
 metis_tac [],

 Cases_on `stmt_exec_ass lval e ((h::t) ++ g_scope_list)` >> (
  fs [is_empty_def]
 ) >>
 Cases_on `separate_exec x` >> (
  gs[]
 ) >>
 PairCases_on ‘x'’ >>
 gvs[stmt_exec_stack_finish_def, AllCaseEqs()] >>
 metis_tac[],

 Cases_on `e_exec (ext_map,func_map,b_func_map) g_scope_list (h::t) e` >> (
  fs [is_empty_def, get_e_ctx_def]
 ) >>
 PairCases_on `x` >>
 fs [] >>
 IMP_RES_TAC e_exec_new_frame >> (
  fs [stmt_exec_stack_finish_def]
 ) >| [
  metis_tac [],

  metis_tac []
 ]
]
QED

Theorem exec_stmt_trans_SOME_REWRS:
!apply_table_f ext_map func_map b_func_map pars_map tbl_map ascope ascope' g_scope_list g_scope_list' funn e stmt_stack frame_list' scope_list status'.
stmt_exec (apply_table_f,ext_map,func_map,b_func_map,pars_map,tbl_map) (ascope, g_scope_list, [(funn, (stmt_trans e)::stmt_stack, scope_list)], status_running) =
        SOME (ascope', g_scope_list', frame_list', status') <=>
 (is_v e ==>
  is_v_str e /\
  ?status''.
   stmt_exec_trans e = SOME status'' /\
   frame_list' = [(funn,stmt_empty::stmt_stack,scope_list)] /\ status' = status'') /\
 (~is_v e ==>
  ?e' frame_list''.
   e_exec (ext_map,func_map,b_func_map) g_scope_list scope_list e = SOME (e', frame_list'') /\
   frame_list' = frame_list'' ++ [(funn,(stmt_trans e')::stmt_stack,scope_list)] /\
   status' = status_running) /\
 g_scope_list' = g_scope_list /\
 scope_list <> [] /\
 ascope' = ascope
Proof
rpt strip_tac >>
Cases_on `scope_list` >> Cases_on `stmt_stack` >> Cases_on `is_v e` >> (
 fs [stmt_exec_def]
) >| [
 Cases_on ‘e’ >> (
  gs[is_v_def]
 ) >>
 Cases_on ‘v’ >> (
  gs[is_v_str_def, stmt_exec_trans_def]
 ) >>
 metis_tac [],

 fs[get_e_ctx_def, AllCaseEqs()] >>
 metis_tac [],

 gs[is_empty_def, AllCaseEqs()] >>
 Cases_on ‘e’ >> (
  gs[is_v_def]
 ) >>
 Cases_on ‘v’ >> (
  gs[is_v_str_def, stmt_exec_trans_def, stmt_exec_stack_finish_def]
 ) >>
 metis_tac [],

 gs[is_empty_def, get_e_ctx_def] >>
 Cases_on ‘e_exec (ext_map,func_map,b_func_map) g_scope_list (h::t) e’ >> (
  fs []
 ) >>
 PairCases_on `x` >>
 fs [] >>
 IMP_RES_TAC e_exec_new_frame >> (
  gvs[stmt_exec_stack_finish_def]
 ) >| [
  metis_tac [],

  metis_tac []
 ]
]
QED

Theorem exec_stmt_cond_SOME_REWRS:
!apply_table_f ext_map func_map b_func_map pars_map tbl_map ascope ascope' g_scope_list g_scope_list' funn e stmt1 stmt2 stmt_stack frame_list' scope_list status'.
stmt_exec (apply_table_f,ext_map,func_map,b_func_map,pars_map,tbl_map) (ascope, g_scope_list, [(funn, (stmt_cond e stmt1 stmt2)::stmt_stack, scope_list)], status_running) =
        SOME (ascope', g_scope_list', frame_list', status') <=>
 (is_v_bool e ==>
  ?b.
   stmt_exec_cond e = SOME b /\
   (b = T ==> frame_list' = [(funn, stmt1::stmt_stack, scope_list)]) /\
   (b = F ==> frame_list' = [(funn, stmt2::stmt_stack, scope_list)])) /\
 (~is_v_bool e ==>
  ?e' frame_list''.
   e_exec (ext_map,func_map,b_func_map) g_scope_list scope_list e = SOME (e', frame_list'') /\
   frame_list' = frame_list'' ++ [(funn, (stmt_cond e' stmt1 stmt2)::stmt_stack, scope_list)]) /\
 g_scope_list' = g_scope_list /\
 scope_list <> [] /\
 ascope' = ascope /\
 status' = status_running
Proof
rpt strip_tac >>
Cases_on `scope_list` >> Cases_on `stmt_stack` >> Cases_on `is_v_bool e` >> (
 fs [stmt_exec_def]
) >| [
 Cases_on `stmt_exec_cond e` >> (
  fs []
 ) >>
 Cases_on `x` >> (
  fs []
 ) >| [
  metis_tac [],

  metis_tac []
 ],

 gs[get_e_ctx_def] >>
 Cases_on `e_exec (ext_map,func_map,b_func_map) g_scope_list (h::t) e` >> (
  fs []
 ) >>
 Cases_on `x` >> (
  fs []
 ) >>
 metis_tac [],

 gs[is_empty_def] >>
 Cases_on `stmt_exec_cond e` >> (
  fs []
 ) >>
 Cases_on `x` >> (
  fs []
 ) >> (
  gvs[stmt_exec_stack_finish_def] >>
  metis_tac []
 ),

 gs[is_empty_def, get_e_ctx_def] >>
 Cases_on `e_exec (ext_map,func_map,b_func_map) g_scope_list (h::t) e` >> (
  fs []
 ) >>
 PairCases_on `x` >>
 fs [] >>
 gs[stmt_exec_stack_finish_def] >>
 IMP_RES_TAC e_exec_new_frame >> (
  fs []
 ) >| [
  metis_tac [],

  metis_tac []
 ]
]
QED

Theorem exec_stmt_app_SOME_REWRS:
!apply_table_f ext_map func_map b_func_map pars_map tbl_map ascope ascope' g_scope_list g_scope_list' funn t_name e_l stmt_stack frame_list' scope_list status'.
stmt_exec (apply_table_f, ext_map, func_map, b_func_map, pars_map, tbl_map) (ascope, g_scope_list, [(funn, (stmt_app t_name e_l)::stmt_stack, scope_list)], status_running) =
        SOME (ascope', g_scope_list', frame_list', status') <=>
 (index_not_const e_l = NONE  ==> ?mk_l f f_args default_f default_f_args. ALOOKUP tbl_map t_name = SOME (mk_l, (default_f, default_f_args)) /\
                       apply_table_f (t_name, e_l, mk_l, (default_f, default_f_args), ascope) = SOME (f, f_args) /\
                       LENGTH mk_l = LENGTH e_l /\
                       frame_list' = [(funn, (stmt_ass lval_null (e_call (funn_name f) f_args))::stmt_stack, scope_list)]) /\
 (!i. index_not_const e_l = SOME i ==>
  ?elem. oEL i e_l = SOME elem /\
  ?e' frame_list''. e_exec (ext_map, func_map, b_func_map) g_scope_list scope_list elem = SOME (e', frame_list'') /\
                    frame_list' = frame_list'' ++ [(funn, (stmt_app t_name (LUPDATE e' i e_l))::stmt_stack, scope_list)]) /\
 g_scope_list' = g_scope_list /\
 scope_list <> [] /\
 ascope' = ascope /\
 status' = status_running
Proof
rpt strip_tac >>
Cases_on `scope_list` >> Cases_on `stmt_stack` >> Cases_on `index_not_const e_l` >> (
 fs [stmt_exec_def]
) >| [
 Cases_on `ALOOKUP tbl_map t_name` >> (
  fs []
 ) >>
 PairCases_on `x` >>
 fs [] >>
 Cases_on `apply_table_f (t_name,e_l,x0,(x1,x2),ascope)` >> (
  fs []
 ) >>
 PairCases_on `x` >> (
  fs []
 ) >>
 gs[] >>
 metis_tac [],

 gvs[AllCaseEqs()] >>
 Cases_on ‘oEL x e_l’ >> (gs[]) >>
 Cases_on `e_exec (ext_map,func_map,b_func_map) g_scope_list (h::t) x'` >> (
  fs []
 ) >>
 PairCases_on `x''` >>
 fs [] >>
 metis_tac [],

 gs[is_empty_def] >>
 Cases_on `ALOOKUP tbl_map t_name` >> (
  fs []
 ) >>
 PairCases_on `x` >>
 fs [] >>
 Cases_on `apply_table_f (t_name,e_l,x0,(x1,x2),ascope)` >> (
  fs []
 ) >>
 PairCases_on `x` >>
 fs [] >>
 Cases_on `LENGTH x0 = LENGTH e_l` >> (
  fs []
 ) >>
 gs[stmt_exec_stack_finish_def] >>
 metis_tac [],

 gvs[is_empty_def, AllCaseEqs()] >>
 Cases_on ‘oEL x e_l’ >> (gs[]) >>
 Cases_on `e_exec (ext_map,func_map,b_func_map) g_scope_list (h::t) x'` >> (
  fs []
 ) >>
 PairCases_on `x''` >>
 gs[] >>
 IMP_RES_TAC e_exec_new_frame >> (
  fs []
 ) >> (
  gvs[stmt_exec_stack_finish_def] >>
  metis_tac []
 )
]
QED

Theorem exec_stmt_ret_SOME_REWRS:
!apply_table_f ext_map func_map b_func_map pars_map tbl_map ascope ascope' g_scope_list g_scope_list' funn e stmt_stack frame_list' scope_list status'.
stmt_exec (apply_table_f,ext_map,func_map,b_func_map,pars_map,tbl_map) (ascope, g_scope_list, [(funn, (stmt_ret e)::stmt_stack, scope_list)], status_running) =
        SOME (ascope', g_scope_list', frame_list', status') <=>
 (!v. get_v e = SOME v ==>
  frame_list' = [(funn,stmt_empty::stmt_stack,scope_list)] /\
  status' = status_returnv v) /\
 (get_v e = NONE ==>
  ?e' frame_list''.
  e_exec (ext_map,func_map,b_func_map) g_scope_list scope_list e = SOME (e', frame_list'') /\
  frame_list' = frame_list'' ++ [(funn,(stmt_ret e')::stmt_stack,scope_list)] /\
  status' = status_running) /\
 g_scope_list' = g_scope_list /\
 scope_list <> [] /\
 ascope' = ascope
Proof
rpt strip_tac >>
Cases_on `scope_list` >> Cases_on `stmt_stack` >> Cases_on `get_v e` >> (
 fs [stmt_exec_def, get_e_ctx_def]
) >| [
 Cases_on `e_exec (ext_map,func_map,b_func_map) g_scope_list (h::t) e` >> (
  fs []
 ) >>
 PairCases_on `x` >>
 fs [] >>
 metis_tac [],

 metis_tac [],

 gs[is_empty_def] >>
 Cases_on `e_exec (ext_map,func_map,b_func_map) g_scope_list (h::t) e` >> (
  fs []
 ) >>
 PairCases_on `x` >>
 fs [] >>
 IMP_RES_TAC e_exec_new_frame >> (
  gvs[stmt_exec_stack_finish_def] >>
  metis_tac []
 ),

 gs[is_empty_def, stmt_exec_stack_finish_def] >>
 metis_tac []
]
QED

Theorem exec_stmt_ext_SOME_REWRS:
!apply_table_f ext_map func_map b_func_map pars_map tbl_map ascope ascope' g_scope_list g_scope_list' funn stmt_stack frame_list' scope_list status'.
stmt_exec (apply_table_f, ext_map, func_map, b_func_map, pars_map, tbl_map) (ascope, g_scope_list, [(funn, stmt_ext::stmt_stack, scope_list)], status_running) =
        SOME (ascope', g_scope_list', frame_list', status') <=>
 (?ext_fun.
   lookup_ext_fun funn ext_map = SOME ext_fun /\
   ?scope_list'' ascope'' status''.
    ext_fun (ascope, g_scope_list, scope_list) = SOME (ascope'', scope_list'', status'') /\
    g_scope_list' = g_scope_list /\
    frame_list' = [(funn, stmt_empty::stmt_stack, scope_list'')] /\
    status' = status'' /\
    scope_list <> [] /\
    ascope' = ascope'')
Proof
rpt strip_tac >>
Cases_on `scope_list` >> Cases_on `stmt_stack` >> (
 fs [stmt_exec_def]
) >| [
 Cases_on `lookup_ext_fun funn ext_map` >> (
  fs []
 ) >>
 Cases_on `x (ascope,g_scope_list,h::t)` >> (
  fs []
 ) >>
 PairCases_on `x'` >>
 fs [] >>
 metis_tac [],

 gs[is_empty_def] >>
 Cases_on `lookup_ext_fun funn ext_map` >> (
  fs []
 ) >>
 Cases_on `x (ascope,g_scope_list,h::t)` >> (
  fs []
 ) >>
 PairCases_on `x'` >>
 gs[stmt_exec_stack_finish_def] >>
 metis_tac []
]
QED

Theorem exec_stmt_block_SOME_REWRS:
!ctx ascope ascope' g_scope_list g_scope_list' funn decl_list stmt stmt_stack frame_list' scope_list status'.
stmt_exec ctx (ascope, g_scope_list, [(funn, (stmt_block decl_list stmt)::stmt_stack, scope_list)], status_running) =
        SOME (ascope', g_scope_list', frame_list', status') <=>
 scope_list <> [] /\
 g_scope_list' = g_scope_list /\
 frame_list' = [(funn, stmt::(stmt_empty::stmt_stack), ((declare_list_in_fresh_scope_exec' decl_list)::(scope_list)))] /\
 ascope' = ascope /\
 status' = status_running
Proof
rpt strip_tac >>
Cases_on `scope_list` >> Cases_on `stmt_stack` >> (
 gvs[stmt_exec_def]
) >- (
 metis_tac[]
) >>
gs[is_empty_def, stmt_exec_stack_finish_def] >>
metis_tac[]
QED

Theorem stmt_exec_block:
!ctx ascope ascope' g_scope_list g_scope_list' funn frame' funn' stmt stmt_stack stmt_stack' h_scope scope_list scope_list' status'.
stmt <> stmt_empty ==>
stmt_exec ctx
          (ascope,g_scope_list,[(funn,stmt::stmt_stack,h_scope::scope_list)],status_running) =
        SOME
          (ascope',g_scope_list',frame'++[(funn',stmt_stack',scope_list')],status') ==>
?stmt_stack''. stmt_stack''++stmt_stack = stmt_stack' /\
stmt_exec ctx
          (ascope,g_scope_list,[(funn,[stmt],h_scope::scope_list)],status_running) =
        SOME
          (ascope',g_scope_list',frame'++[(funn',stmt_stack'',scope_list')],status')
Proof
rpt strip_tac >>
Cases_on `stmt` >> (
 fs [] >>
 PairCases_on ‘ctx’
) >| [
 (* Assign *)
 gs[exec_stmt_ass_SOME_REWRS] >>
 Cases_on `is_v e` >> (
  fs []
 ),

 (* Conditional *)
 fs [exec_stmt_cond_SOME_REWRS] >>
 Cases_on `is_v_bool e` >> (
  fs []
 ) >>
 Cases_on `b` >> (
  fs []
 ),

 (* Block entry *)
 fs [exec_stmt_block_SOME_REWRS],

 (* Return *)
 fs [exec_stmt_ret_SOME_REWRS] >>
 Cases_on `get_v e` >> (
  fs []
 ),

 (* Seq *)
 Cases_on `stmt_stack` >> (
  fs []
 ) >>
 fs [stmt_exec_def, is_empty_def] >>
 Cases_on `is_empty s` >> (
  fs [stmt_exec_stack_finish_def]
 ) >>
 Cases_on `stmt_exec (ctx0,ctx1,ctx2,ctx3,ctx4,ctx5)
               (ascope,g_scope_list,[(funn,[s],h_scope::scope_list)],status_running)` >> (
  fs []
 ) >>
 PairCases_on `x` >> (
  gvs[stmt_exec_seq_finish_def, AllCaseEqs()]
 ) >> (
  gs[stmt_exec_stack_finish_def]
 ) >>
 PairCases_on ‘frame’ >>
 gs[] >>
 Cases_on ‘frame1’ >> (gs[]) >>
 Cases_on ‘t'’ >- (
  FULL_SIMP_TAC list_ss [] >>
  rw[] >> (
   Cases_on ‘frame'’ >> (
    gs[]
   )
  )
 ) >>
 gs[] >>
 gs[AllCaseEqs()],

 (* Transition *)
 gs[exec_stmt_trans_SOME_REWRS] >>
 Cases_on `is_v e` >> (
  gs[]
 ),

 (* Apply *)
 gs[exec_stmt_app_SOME_REWRS] >>
 Cases_on `index_not_const l` >> (
  gs[]
 ),

 (* Extern *)
 fs[exec_stmt_ext_SOME_REWRS]
]
QED

Theorem stmt_exec_block_sing:
!ctx ascope ascope' g_scope_list g_scope_list' funn funn' stmt stmt_stack stmt_stack' h_scope scope_list scope_list' status'.
stmt <> stmt_empty ==>
stmt_exec ctx
          (ascope,g_scope_list,[(funn,stmt::stmt_stack,h_scope::scope_list)],status_running) =
        SOME
          (ascope',g_scope_list',[(funn',stmt_stack',scope_list')],status') ==>
?stmt_stack''. stmt_stack''++stmt_stack = stmt_stack' /\
stmt_exec ctx
          (ascope,g_scope_list,[(funn,[stmt],h_scope::scope_list)],status_running) =
        SOME
          (ascope',g_scope_list',[(funn',stmt_stack'',scope_list')],status')
Proof
rpt strip_tac >>
IMP_RES_TAC (Q.SPECL [`ctx`, `ascope`, `ascope'`, `g_scope_list`, `g_scope_list'`, `funn`, `[]`] stmt_exec_block) >>
fs [listTheory.APPEND_NIL]
QED

(* This tracks some invariants of stmt_exec under regular conditions,
 * i.e. funn of current frame, ... *)
Theorem stmt_exec_inv_sing:
!ctx ascope ascope' g_scope_list g_scope_list' frame' funn funn' stmt_stack stmt_stack' scope_list scope_list' status status'.
stmt_exec ctx (ascope, g_scope_list, [(funn,stmt_stack,scope_list)], status) =
 SOME (ascope', g_scope_list', frame'++[(funn',stmt_stack',scope_list')], status') ==>
funn = funn' /\
(frame' = [] \/
 (status' = status_running /\
 ?funn'' stmt' scope'.
  frame' = [(funn'', [stmt'], [scope'])])
)
Proof
`!ctx ascope g_scope_list funn stmt_stack scope_list status.
 (\ctx' state'.
  !ascope' g_scope_list' funn' stmt_stack' scope_list' status' ascope'' g_scope_list'' frame'' funn'' stmt_stack'' scope_list'' status''.
  state' = (ascope',g_scope_list',[(funn',stmt_stack',scope_list')],status') ==>
  stmt_exec ctx' (ascope',g_scope_list',[(funn',stmt_stack',scope_list')],status') =
   SOME (ascope'', g_scope_list'', frame''++[(funn'',stmt_stack'',scope_list'')], status'') ==>
  (funn' = funn'' /\
   (frame'' = [] \/
    (status'' = status_running /\
     ?funn''' stmt'' scope''.
      frame'' = [(funn''', [stmt''], [scope''])]
   )))
 ) ctx (ascope, g_scope_list, [(funn,stmt_stack,scope_list)], status)` suffices_by (
 metis_tac []
) >>
rpt strip_tac >>
irule stmt_exec_ind >>
rpt strip_tac >| [
 (* Apply *)
 fs [exec_stmt_app_SOME_REWRS] >>
 rpt strip_tac >> (
  Cases_on `index_not_const e_l` >> (
   fs []
  )
 ) >>
 metis_tac [e_exec_new_frame],

 (* Extern *)
 rename1 `[(funn,[stmt_ext],scope::scope_list)]` >>
 fs [stmt_exec_def] >>
 Cases_on `lookup_ext_fun funn ext_map` >> (
  fs []
 ) >>
 Cases_on `x (ascope,g_scope_list,scope::scope_list)` >> (
  fs []
 ) >>
 PairCases_on `x'` >> (
  fs []
 ),

 (* Return *)
 PairCases_on ‘ctx’ >>
 fs [exec_stmt_ret_SOME_REWRS] >>
 rpt strip_tac >> (
  Cases_on `get_v e` >> (
   fs []
  )
 ) >>
 metis_tac [e_exec_new_frame],

 (* Trans *)
 PairCases_on ‘ctx’ >>
 fs [exec_stmt_trans_SOME_REWRS] >>
 metis_tac [e_exec_new_frame],

 (* Cond *)
 PairCases_on ‘ctx’ >>
 fs [exec_stmt_cond_SOME_REWRS] >>
 rpt strip_tac >> (
  Cases_on ‘is_v_bool e’ >> (
   gs[] >>
   metis_tac[e_exec_new_frame]
  )
 ),

 fs [stmt_exec_def],

 fs [stmt_exec_def],

 fs [stmt_exec_def],

 fs [stmt_exec_def],

 PairCases_on ‘ctx’ >>
 fs [exec_stmt_ass_SOME_REWRS] >>
 metis_tac [e_exec_new_frame],

 (* Seq *)
 fs[stmt_exec_def, AllCaseEqs()] >>
 rename1 `[(funn,[stmt1],scope::scope_list)]` >>
 Cases_on `stmt_exec ctx
               (ascope,g_scope_list,[(funn,[stmt1],scope::scope_list)],status_running)` >> (
  fs []
 ) >>
 PairCases_on `x` >>
 fs [] >>
 Cases_on `x2` >> (
  fs [stmt_exec_seq_finish_def]
 ) >>
 Cases_on `t` >> (
  fs []
 ) >| [
  PairCases_on `h` >>
  fs [] >>
  Cases_on `h1` >> (
   fs []
  ) >>
  Cases_on `t` >> (
   fs []
  ) >| [
   Cases_on `x3` >> (
    fs[] >>
    Cases_on ‘is_empty stmt1’ >> (
     gs[]
    )
   ),

   Cases_on `t'` >> (
    fs []
   ) >>
   Cases_on `x3` >> (
    fs[] >>
    Cases_on ‘is_empty stmt1’ >> (
     gs[]
    )
   )
  ],

  Cases_on `t'` >> (
   fs []
  ) >>
  PairCases_on `h'` >>
  gs[AllCaseEqs()] >>
  Cases_on ‘is_empty stmt1’ >> (
   gvs[]
  ) >>
  rpt strip_tac >> (
   gvs[]
  )
 ],

 (* TODO: Lots of duplication here... *)
 (* TODO: Why does AllCaseEqs loop? *)
 fs [stmt_exec_def, AllCaseEqs()] >>
 Cases_on ‘is_empty stmt’ >> (
  gvs[]
 ) >>
 rpt strip_tac >- (
  PairCases_on ‘state'’ >>
  FULL_SIMP_TAC std_ss [stmt_exec_stack_finish_def] >>
  Cases_on ‘state'2’ >> (
   gs[]
  ) >>
  PairCases_on ‘h’ >>
  gs[] >>
  Cases_on ‘h1’ >> (
   gs[]
  ) >>
  Cases_on ‘t’ >> (
   gs[]
  ) >- (
   gs[AllCaseEqs()]
  ) >>
  Cases_on ‘t'’ >> (
   gs[]
  ) >- (
   PairCases_on ‘h'’ >>
   gs[] >>
   Cases_on ‘h'1’ >> (
    gs[]
   ) >>
   Cases_on ‘t’ >> (
    gs[]
   ) >>
   Cases_on ‘t''’ >> (
    FULL_SIMP_TAC std_ss []
   ) >- (
    rw[] >>
    FULL_SIMP_TAC list_ss [] >>
    rw[] >>
    ‘h'0 = funn''’ by (
     Cases_on ‘frame''’ >> (
      gs[]
     )
    ) >>
    rw[]
   ) >>
   Cases_on ‘t’ >> (
    gs[]
   )
  ) >>
  Cases_on ‘t’ >> (
   gs[]
  )
 ) >>
 (* Property of stmt_exec_stack_finish? *)
 PairCases_on ‘state'’ >>
 FULL_SIMP_TAC std_ss [stmt_exec_stack_finish_def] >>
 Cases_on ‘state'2’ >> (
  gs[]
 ) >>
 PairCases_on ‘h’ >>
 gs[] >>
 Cases_on ‘h1’ >> (
  gs[]
 ) >>
 Cases_on ‘t’ >> (
  gs[]
 ) >- (
  gs[AllCaseEqs()]
 ) >>
 Cases_on ‘t'’ >> (
  gs[]
 ) >- (
  PairCases_on ‘h'’ >>
  gs[] >>
  Cases_on ‘h'1’ >> (
   gs[]
  ) >>
  Cases_on ‘t’ >> (
   gs[]
  ) >>
  Cases_on ‘t''’ >> (
   FULL_SIMP_TAC std_ss []
  ) >- (
   rw[] >>
   FULL_SIMP_TAC list_ss [] >>
   rw[] >>
   ‘h'0 = funn''’ by (
    Cases_on ‘frame''’ >> (
     gs[]
    )
   ) >>
   rw[] >>
   Cases_on ‘frame''’ >> (
    gs[]
   ) >>
   metis_tac[]
  ) >>
  Cases_on ‘t’ >> (
   gs[]
  )
 ) >>
 Cases_on ‘t’ >> (
  gs[]
 ),

 fs [stmt_exec_def],

 fs [stmt_exec_def],

 fs [stmt_exec_def],

 fs [stmt_exec_def]
]
(*
 (* Trans (stack case) *)
 PairCases_on ‘ctx’ >>
 fs [exec_stmt_trans_SOME_REWRS] >>
 metis_tac [],

 (* Cond *)
 fs [exec_stmt_cond_SOME_REWRS] >>
 metis_tac [e_exec_new_frame],

 (* Cond (stack case) *)
 fs [exec_stmt_cond_SOME_REWRS] >>
 metis_tac [],

 (* Apply (stack case) *)
 rename1 `stmt_app t_name e_l` >>
 fs [] >>
 rpt strip_tac >> (
  subgoal `stmt_app t_name e_l <> stmt_empty` >- (
   fs []
  ) >>
  IMP_RES_TAC stmt_exec_block >>
  fs [exec_stmt_app_SOME_REWRS]
 ),

 (* Block entry *)
 fs [exec_stmt_block_SOME_REWRS],

 fs [stmt_exec_def],

 (* Block exit *)
 fs [stmt_exec_def] >>
 Cases_on `stmt_stack` >> (
  fs []
 ),

 fs [stmt_exec_def],

 (* Assign *)
 fs [exec_stmt_ass_SOME_REWRS] >>
 metis_tac [e_exec_new_frame],

 (* Assign (stack case) *)
 fs [exec_stmt_ass_SOME_REWRS] >>
 metis_tac [],

 (* Extern (stack case) *)
 fs [] >>
 rpt strip_tac >>
 subgoal `stmt_ext <> stmt_empty` >- (
  fs []
 ) >>
 IMP_RES_TAC stmt_exec_block >>
 fs [exec_stmt_ext_SOME_REWRS],

 (* Seq *)
 fs [stmt_exec_def] >>
 Cases_on `is_empty stmt1` >> (
  fs []
  ) >>
 rename1 `[(funn,[stmt1],scope::scope_list)]` >>
 Cases_on `stmt_exec ctx
               (ascope,g_scope_list,[(funn,[stmt1],scope::scope_list)],status_running)` >> (
  fs []
 ) >>
 PairCases_on `x` >>
 fs [] >>
 Cases_on `x2` >> (
  fs []
 ) >>
 Cases_on `t` >> (
  fs []
 ) >| [
  PairCases_on `h` >>
  fs [] >>
  Cases_on `h1` >> (
   fs []
  ) >>
  Cases_on `t` >> (
   fs []
  ) >| [
   Cases_on `x3` >> (
    fs []
   ),

   Cases_on `t'` >> (
    fs []
   ) >>
   Cases_on `x3` >> (
    fs []
   )
  ],

  Cases_on `t'` >> (
   fs []
  ) >>
  Cases_on `x3` >> (
   fs []
  ) >>
  PairCases_on `h'` >>
  fs [] >>
  Cases_on `h'1` >> (
   fs []
  ) >>
  Cases_on `t` >> (
   fs []
  )
 ],

 (* Seq (stack case) *)
 fs [] >>
 rpt strip_tac >>
 rename1 `stmt_seq stmt1 stmt2` >>
 subgoal `stmt_seq stmt1 stmt2 <> stmt_empty` >- (
  fs []
 ) >>
 IMP_RES_TAC stmt_exec_block >>
 fs [stmt_exec_def],

 (* Initial trans status *)
 fs [stmt_exec_def],

 (* Initial return status *)
 fs [stmt_exec_def],

 fs [],

 fs []
]
*)
QED

Theorem stmt_exec_inv_sing_noframe:
!ctx ascope ascope' g_scope_list g_scope_list' funn funn' stmt_stack stmt_stack' scope_list scope_list' status status'.
stmt_exec ctx (ascope, g_scope_list, [(funn,stmt_stack,scope_list)], status) =
 SOME (ascope', g_scope_list', [(funn',stmt_stack',scope_list')], status') ==>
funn = funn'
Proof
rpt strip_tac >>
ASSUME_TAC (Q.SPECL [`ctx`, `ascope`, `ascope'`, `g_scope_list`, `g_scope_list'`, `[]`] stmt_exec_inv_sing) >>
fs [listTheory.APPEND_NIL] >>
metis_tac []
QED

(* This states a property of the steps where the final status is Return *)
Theorem stmt_exec_status_returnv_inv:
!ctx ascope ascope' g_scope_list g_scope_list' funn stmt_stack scope_list frame_list' v.
stmt_exec ctx (ascope, g_scope_list, [(funn, stmt_stack, scope_list)], status_running) =
        SOME (ascope', g_scope_list', frame_list', status_returnv v) ==>
 ?stmt_stack' scope_list'.
 LENGTH stmt_stack = LENGTH stmt_stack' /\
 frame_list' = [(funn, stmt_stack', scope_list')]
Proof
`!ctx ascope g_scope_list funn stmt_stack scope_list.
 (\ctx' state'.
  !ascope' g_scope_list' funn' stmt_stack' scope_list' ascope'' g_scope_list'' frame_list'' v''.
  state' = (ascope',g_scope_list',[(funn',stmt_stack',scope_list')],status_running) ==>
  stmt_exec ctx' (ascope',g_scope_list',[(funn',stmt_stack',scope_list')],status_running) =
   SOME (ascope'', g_scope_list'', frame_list'', status_returnv v'') ==>
  (?stmt_stack'' scope_list''.
   LENGTH stmt_stack' = LENGTH stmt_stack'' /\
   frame_list'' = [(funn', stmt_stack'', scope_list'')])
 ) ctx (ascope, g_scope_list, [(funn,stmt_stack,scope_list)], status_running)` suffices_by (
 metis_tac []
) >>
rpt strip_tac >>
irule stmt_exec_ind >>
rpt strip_tac >| [
 fs [exec_stmt_app_SOME_REWRS],

 fs [exec_stmt_ext_SOME_REWRS] >>
 rpt strip_tac >>
 qexistsl_tac [`[stmt_empty]`, `scope_list''`] >>
 fs [],

 PairCases_on ‘ctx’ >>
 fs [exec_stmt_ret_SOME_REWRS] >>
 Cases_on `get_v e` >> (
  fs []
 ),

 PairCases_on ‘ctx’ >>
 fs[exec_stmt_trans_SOME_REWRS],

 PairCases_on ‘ctx’ >>
 fs [exec_stmt_cond_SOME_REWRS],

 fs [exec_stmt_block_SOME_REWRS],

 fs [stmt_exec_def],

 fs [stmt_exec_def],

 fs [stmt_exec_def],

 PairCases_on ‘ctx’ >>
 fs [exec_stmt_ass_SOME_REWRS], 

 gs[] >>
 rename1 `[(funn,[stmt_seq stmt1 stmt2],scope::scope_list)]` >>
 rpt strip_tac >>
 gs[stmt_exec_def, AllCaseEqs()] >>
 PairCases_on ‘state'’ >>
 gs[stmt_exec_seq_finish_def, AllCaseEqs()],

 (* OLD
 FULL_SIMP_TAC bool_ss [] >>
 rename1 `[(funn,[stmt_seq stmt1 stmt2],scope::scope_list)]` >>
 rpt strip_tac >> (
  PairCases_on ‘ctx’ >>
  fs [exec_stmt_seq_SOME_REWRS] >>
  rw [] >>
  Cases_on `is_empty stmt1` >> (
   fs []
  ) >| [
   fs [stmt_exec_def],

   fs [exec_stmt_seq_SOME_REWRS]
  ]
 ),
 *)

 gs[stmt_exec_def, AllCaseEqs()] >>
 Cases_on `is_empty stmt` >> (
  gs[]
 ) >>
 rpt strip_tac >>
 PairCases_on ‘state'’ >>
 gvs[stmt_exec_stack_finish_def, AllCaseEqs()],

 gs[stmt_exec_def],

 gs[stmt_exec_def],
  
 gs[stmt_exec_def],

 gs[stmt_exec_def]
]
QED

(* This states a property of the steps where the final status is Transition *)
Theorem stmt_exec_status_trans_inv:
!ctx ascope ascope' g_scope_list g_scope_list' funn stmt_stack scope_list frame_list' x.
stmt_exec ctx (ascope, g_scope_list, [(funn, stmt_stack, scope_list)], status_running) =
        SOME (ascope', g_scope_list', frame_list', status_trans x) ==>
 ?stmt_stack' scope_list'.
 LENGTH stmt_stack = LENGTH stmt_stack' /\
 frame_list' = [(funn, stmt_stack', scope_list')]
Proof
`!ctx ascope g_scope_list funn stmt_stack scope_list.
 (\ctx' state'.
  !ascope' g_scope_list' funn' stmt_stack' scope_list' ascope'' g_scope_list'' frame_list'' x''.
  state' = (ascope',g_scope_list',[(funn',stmt_stack',scope_list')],status_running) ==>
  stmt_exec ctx' (ascope',g_scope_list',[(funn',stmt_stack',scope_list')],status_running) =
   SOME (ascope'', g_scope_list'', frame_list'', status_trans x'') ==>
  (?stmt_stack'' scope_list''.
   LENGTH stmt_stack' = LENGTH stmt_stack'' /\
   frame_list'' = [(funn', stmt_stack'', scope_list'')])
 ) ctx (ascope, g_scope_list, [(funn,stmt_stack,scope_list)], status_running)` suffices_by (
 metis_tac []
) >>
rpt strip_tac >>
irule stmt_exec_ind >>
rpt strip_tac >| [
 fs [exec_stmt_app_SOME_REWRS],

 fs [exec_stmt_ext_SOME_REWRS] >>
 rpt strip_tac >>
 qexistsl_tac [`[stmt_empty]`, `scope_list''`] >>
 fs [],

 PairCases_on ‘ctx’ >>
 fs [exec_stmt_ret_SOME_REWRS] >>
 Cases_on `get_v e` >> (
  fs []
 ),

 PairCases_on ‘ctx’ >>
 fs[exec_stmt_trans_SOME_REWRS],

 PairCases_on ‘ctx’ >>
 fs [exec_stmt_cond_SOME_REWRS],

 fs [exec_stmt_block_SOME_REWRS],

 fs [stmt_exec_def],

 fs [stmt_exec_def],

 fs [stmt_exec_def],

 PairCases_on ‘ctx’ >>
 fs [exec_stmt_ass_SOME_REWRS], 

 gs[] >>
 rename1 `[(funn,[stmt_seq stmt1 stmt2],scope::scope_list)]` >>
 rpt strip_tac >>
 gs[stmt_exec_def, AllCaseEqs()] >>
 PairCases_on ‘state'’ >>
 gs[stmt_exec_seq_finish_def, AllCaseEqs()],

 (* OLD
 FULL_SIMP_TAC bool_ss [] >>
 rename1 `[(funn,[stmt_seq stmt1 stmt2],scope::scope_list)]` >>
 rpt strip_tac >> (
  PairCases_on ‘ctx’ >>
  fs [exec_stmt_seq_SOME_REWRS] >>
  rw [] >>
  Cases_on `is_empty stmt1` >> (
   fs []
  ) >| [
   fs [stmt_exec_def],

   fs [exec_stmt_seq_SOME_REWRS]
  ]
 ),
 *)

 gs[stmt_exec_def, AllCaseEqs()] >>
 Cases_on `is_empty stmt` >> (
  gs[]
 ) >>
 rpt strip_tac >>
 PairCases_on ‘state'’ >>
 gvs[stmt_exec_stack_finish_def, AllCaseEqs()],

 gs[stmt_exec_def],

 gs[stmt_exec_def],
  
 gs[stmt_exec_def],

 gs[stmt_exec_def]
]
QED


Theorem exec_stmt_seq_SOME_REWRS:
!ctx ascope ascope' g_scope_list g_scope_list' funn stmt1 stmt2 stmt_stack frame_list' scope_list status'.
stmt_exec ctx (ascope, g_scope_list, [(funn, (stmt_seq stmt1 stmt2)::stmt_stack, scope_list)], status_running) =
        SOME (ascope', g_scope_list', frame_list', status') <=>
 scope_list <> [] /\
 (is_empty stmt1 ==>
  g_scope_list' = g_scope_list /\
  frame_list' = [(funn, stmt2::stmt_stack, scope_list)] /\
  ascope' = ascope /\
  status' = status_running) /\
 (~is_empty stmt1 ==>
  ?g_scope_list'' frame_list'' ascope'' status''.
   stmt_exec ctx (ascope, g_scope_list, [(funn, [stmt1], scope_list)], status_running) =
    SOME (ascope'', g_scope_list'', frame_list'', status'') /\
   g_scope_list' = g_scope_list'' /\
   ascope' = ascope'' /\
   status' = status'' /\ (
   (?stmt1' scope_list'.
     frame_list'' = [(funn, [stmt1'], scope_list')] /\
     (status'' = status_running ==> frame_list' = [(funn, (stmt_seq stmt1' stmt2)::stmt_stack, scope_list')]) /\
     (status'' <> status_running ==> frame_list' = [(funn, stmt1'::stmt_stack, scope_list')])) \/
   (?stmt1' stmt1'' scope_list'.
     frame_list'' = [(funn, stmt1''::([stmt1']), scope_list')] /\
     status'' = status_running /\
     frame_list' = [(funn, stmt1''::((stmt_seq stmt1' stmt2)::stmt_stack), scope_list')]
     ) \/
   (?stmt1' funn' stmt' scope' scope_list'.
     frame_list'' = ((funn', [stmt'], [scope'])::[(funn, [stmt1'], scope_list')]) /\
     status'' = status_running /\
     frame_list' = ((funn', [stmt'], [scope'])::[(funn, (stmt_seq stmt1' stmt2)::stmt_stack, scope_list')]))))
Proof
rpt strip_tac >>
Cases_on `scope_list` >> Cases_on `stmt_stack` >> Cases_on `is_empty stmt1` >> (
 gs[stmt_exec_def]
) >- (
 metis_tac[]
) >- (
 Cases_on `stmt_exec ctx
             (ascope,g_scope_list,[(funn,[stmt1],h::t)],status_running)` >> (
  gs[]
 ) >>
 PairCases_on `x` >>
 gs[stmt_exec_seq_finish_def] >>
 gs[AllCaseEqs()] >>
 Cases_on ‘x2’ >> (
  gs[]
 ) >>
 Cases_on `t'` >> (
  gs[]
 ) >- (
  PairCases_on `h'` >>
  gs[] >>
  Cases_on `h'1` >> (
   gs[]
  ) >>
  Cases_on `status'` >> (
   gs[]
  ) >- (
   Cases_on `x3` >> (
    gs[]
   ) >- (
    metis_tac[stmt_exec_inv_sing_noframe]
   ) >- (
    rpt strip_tac >>
    gvs[] >>
    imp_res_tac stmt_exec_status_returnv_inv >>
    gvs[]
   ) >>
   rpt strip_tac >>
   gvs[] >>
   imp_res_tac stmt_exec_status_trans_inv >>
   gvs[]
  ) >>
  Cases_on `x3` >> (
   gs[]
  ) >>
  metis_tac[stmt_exec_inv_sing_noframe]
 ) >>
 (* Some kind of equivalence... *)
 EQ_TAC >- (
  rpt strip_tac >>
  ( gs[] ) >> (
   assume_tac $ Q.SPECL [‘ctx’, ‘ascope’, ‘ascope'’, ‘g_scope_list’, ‘g_scope_list'’, ‘[h']’] stmt_exec_inv_sing >>
   gs[] >>
   metis_tac[]
  )
 ) >>
 rpt strip_tac >> ( gs[] )
(*
  >> (
  EQ_TAC >- (
   rpt strip_tac >>
   ( gs[] ) >- (
    gvs[] >>
    (* New frame, then status must have been Running *)
    stmt_exec_inv_sing
    cheat
   ) >>
   gvs[] >>
   ‘?funn'' stmt' scope'.
    h' = (funn'',[stmt'],[scope']) /\ funn' = funn’ suffices_by (
    rpt strip_tac >>
    metis_tac[]
   ) >>
   (* If a new frame was added, then this has a single-entry
    * statement stack and scope stack, and the bottom frame has
    * the same function name *)
   assume_tac $ Q.SPECL [‘ctx’, ‘ascope’, ‘ascope'’, ‘g_scope_list’, ‘g_scope_list'’, ‘[h']’] stmt_exec_inv_sing >>
   gs[] >>
   metis_tac[]
  ) >>
 
*)
(*  
  PairCases_on `h'` >>
  fs [] >>
  Cases_on `h'1` >> (
   fs []
  ) >>
  Cases_on `t'` >> (
   fs []
  ) >| [
   Cases_on `x3` >> (
    Cases_on `status'` >> (
     fs []
    )
   ) >> (
    metis_tac [stmt_exec_inv_sing_noframe]
   ),

   Cases_on `t''` >> (
    fs []
   ) >>
   Cases_on `x3` >> (
    Cases_on `status'` >> (
     fs []
    )
   ) >>
   (* ??? *)
   cheat
(*
   metis_tac [stmt_exec_inv_sing_noframe]
*)
  ],

  Cases_on `t''` >> (
   fs []
  ) >>
  Cases_on `x3` >> (
   fs []
  ) >- (
   PairCases_on `h''` >>
   fs [] >>
   Cases_on `h''1` >> (
    fs []
   ) >>
   Cases_on `t'` >> (
    fs []
   ) >>
   assume_tac (Q.SPECL [`ctx`, `ascope`, `x0`, `g_scope_list`, `x1`, `[h']`] stmt_exec_inv_sing) >>
   fs [] >>
   RES_TAC >>
   `funn = h''0` suffices_by (
    metis_tac []
   ) >>
   fs [] >>
   metis_tac []
  ) >> (
   Cases_on `status'` >> (
    gvs[]
   ) >>
   (* ??? *)
   cheat
  ),

  cheat
 ]
*)
) >- (
 gs[is_empty_def, stmt_exec_stack_finish_def] >>
 metis_tac []
) >>
gs[is_empty_def, stmt_exec_stack_finish_def] >>
Cases_on `stmt_exec ctx
            (ascope,g_scope_list,[(funn,[stmt1],h::t)],status_running)` >> (
 fs []
) >>
PairCases_on `x` >>
gs[stmt_exec_seq_finish_def] >>
Cases_on `x2` >> (
 fs []
) >>
Cases_on `t''` >> (
 fs [stmt_exec_stack_finish_def]
) >| [
 PairCases_on `h''` >>
 fs [] >>
 Cases_on `h''1` >> (
  fs []
 ) >>
 Cases_on `t''` >> (
  fs []
 ) >| [
  Cases_on `x3` >> (
   fs [stmt_exec_stack_finish_def] >>
   Cases_on `status'` >> (
    fs[]
   ) >>
   metis_tac [stmt_exec_inv_sing_noframe]
  ),

  Cases_on `t'''` >> (
   fs [stmt_exec_stack_finish_def]
  ) >>
  Cases_on `x3` >> (
   fs [stmt_exec_stack_finish_def] >>
   Cases_on `status'` >> (
    fs[]
   )
  ) >- (
   metis_tac [stmt_exec_inv_sing_noframe]
  ) >- (
   rpt strip_tac >>
   gvs[] >>
   imp_res_tac stmt_exec_status_returnv_inv >>
   gvs[]
(*
   (* New function frame with status return *)
   cheat
*)
  ) >>
  rpt strip_tac >>
  gvs[] >>
  imp_res_tac stmt_exec_status_trans_inv >>
  gvs[]
(*
  (* New function frame with status trans *)
  cheat
*)
 ],

 Cases_on `t'''` >> (
  fs []
 ) >>
 PairCases_on `h'''` >>
 gs[] >>
 Cases_on `h'''1` >> (
  fs []
 ) >>
 Cases_on `t''` >> (
  fs [stmt_exec_stack_finish_def]
 ) >>
 Cases_on `x3` >> (
  fs []
 ) >| [
  (* Running *)
  PairCases_on `h''` >>
  fs [] >>
  Cases_on `h''1` >> (
   fs []
  ) >>
  assume_tac (Q.SPECL [`ctx`, `ascope`, `x0`, `g_scope_list`, `x1`, `[(h''0,h''::t'',h''2)]`] stmt_exec_inv_sing) >>
  fs [] >>
  RES_TAC >>
  Cases_on `t''` >> (
   fs []
  ) >>
  metis_tac [],

  (* Return *)
  PairCases_on `h''` >>
  fs [] >>
  Cases_on `h''1` >> (
   fs []
  ) >>
  Cases_on `t''` >> (
   fs []
  ) >- (
   Cases_on ‘status'’ >> (
    gs[]
   ) >>
   rpt strip_tac >>
   gvs[] >>

   assume_tac $ Q.SPECL [‘ctx’, ‘ascope’, ‘ascope'’, ‘g_scope_list’, ‘g_scope_list'’, ‘[(h''0,[h''],h''2)]’] stmt_exec_inv_sing >>
   gs[] >>
   res_tac >>
   gs[]
  ) >>
  simp[AllCaseEqs()],

  (* Transition *)
  PairCases_on `h''` >>
  fs [] >>
  Cases_on `h''1` >> (
   fs []
  ) >>
  Cases_on `t''` >> (
   fs []
  ) >- (
   Cases_on ‘status'’ >> (
    gs[]
   ) >>


   assume_tac $ Q.SPECL [‘ctx’, ‘ascope’, ‘x0’, ‘g_scope_list’, ‘x1’, ‘[(h''0,[h''],h''2)]’] stmt_exec_inv_sing >>
   gs[] >>
   res_tac >>
   gs[]
  ) >>
  simp[AllCaseEqs()]
 ]
]
(*
rpt strip_tac >>
Cases_on `scope_list` >> Cases_on `stmt_stack` >> Cases_on `is_empty stmt1` >> (
 fs [stmt_exec_def]
) >| [
 metis_tac [],

 Cases_on `stmt_exec ctx
             (ascope,g_scope_list,[(funn,[stmt1],h::t)],status_running)` >> (
  fs []
 ) >>
 PairCases_on `x` >>
 gs[stmt_exec_seq_finish_def] >>
 Cases_on `x2` >> (
  fs []
 ) >>
 Cases_on `t'` >> (
  fs []
 ) >| [
  PairCases_on `h'` >>
  fs [] >>
  Cases_on `h'1` >> (
   fs []
  ) >>
  Cases_on `t'` >> (
   fs []
  ) >| [
   Cases_on `x3` >> (
    Cases_on `status'` >> (
     fs []
    )
   ) >> (
    metis_tac [stmt_exec_inv_sing_noframe]
   ),

   Cases_on `t''` >> (
    fs []
   ) >>
   Cases_on `x3` >> (
    Cases_on `status'` >> (
     fs []
    )
   ) >>
   (* ??? *)
   cheat
(*
   metis_tac [stmt_exec_inv_sing_noframe]
*)
  ],

  Cases_on `t''` >> (
   fs []
  ) >>
  Cases_on `x3` >> (
   fs []
  ) >- (
   PairCases_on `h''` >>
   fs [] >>
   Cases_on `h''1` >> (
    fs []
   ) >>
   Cases_on `t'` >> (
    fs []
   ) >>
   assume_tac (Q.SPECL [`ctx`, `ascope`, `x0`, `g_scope_list`, `x1`, `[h']`] stmt_exec_inv_sing) >>
   fs [] >>
   RES_TAC >>
   `funn = h''0` suffices_by (
    metis_tac []
   ) >>
   fs [] >>
   metis_tac []
  ) >> (
   Cases_on `status'` >> (
    gvs[]
   ) >>
   (* ??? *)
   cheat
  )
 ],

 gs[is_empty_def, stmt_exec_stack_finish_def] >>
 metis_tac [],

 gs[is_empty_def, stmt_exec_stack_finish_def] >>
 Cases_on `stmt_exec ctx
             (ascope,g_scope_list,[(funn,[stmt1],h::t)],status_running)` >> (
  fs []
 ) >>
 PairCases_on `x` >>
 fs [] >>
 Cases_on `x2` >> (
  fs []
 ) >>
 Cases_on `t''` >> (
  fs [stmt_exec_stack_finish_def]
 ) >| [
  PairCases_on `h''` >>
  fs [] >>
  Cases_on `h''1` >> (
   fs []
  ) >>
  Cases_on `t''` >> (
   fs []
  ) >| [
   Cases_on `x3` >> (
    Cases_on `status'` >> (
     fs []
    )
   ) >> (
    metis_tac [stmt_exec_inv_sing_noframe]
   ),

   Cases_on `t'''` >> (
    fs []
   ) >>
   Cases_on `x3` >> (
    Cases_on `status'` >> (
     fs []
    )
   ) >>
   metis_tac [stmt_exec_inv_sing_noframe]
  ],

  Cases_on `t'''` >> (
   fs []
  ) >>
  Cases_on `x3` >> (
   Cases_on `status'` >> (
    fs []
   )
  ) >> (
   PairCases_on `h'''` >>
   fs [] >>
   Cases_on `h'''1` >> (
    fs []
   ) >>
   Cases_on `t''` >> (
    fs []
   )
  ) >| [
   (* Running *)
   PairCases_on `h''` >>
   fs [] >>
   Cases_on `h''1` >> (
    fs []
   ) >>
   assume_tac (Q.SPECL [`uninit`, `ctx`, `ascope`, `x0`, `g_scope_list`, `x1`, `[(h''0,h''::t'',h''2)]`] stmt_exec_inv_sing) >>
   fs [] >>
   RES_TAC >>
   Cases_on `t''` >> (
    fs []
   ) >>
   metis_tac [],

   (* Return *)
   PairCases_on `h''` >>
   fs [] >>
   Cases_on `h''1` >> (
    fs []
   ) >>
   Cases_on `t''` >> (
    fs []
   ) >>
   Cases_on `t'''` >> (
    fs []
   ),

   (* Transition *)
   PairCases_on `h''` >>
   fs [] >>
   Cases_on `h''1` >> (
    fs []
   ) >>
   Cases_on `t''` >> (
    fs []
   ) >>
   Cases_on `t'''` >> (
    fs []
   )
  ]
 ]
]
*)
QED

(* TODO: Make use of something like the below
val exec_stmt_REWRS =
  [exec_stmt_ext_SOME_REWRS,
   exec_stmt_app_SOME_REWRS,
   exec_stmt_ret_SOME_REWRS,
   exec_stmt_trans_SOME_REWRS,
   exec_stmt_cond_SOME_REWRS,
   exec_stmt_block_SOME_REWRS,
   exec_stmt_ass_SOME_REWRS,
   exec_stmt_seq_SOME_REWRS];
*)


(* Reduction of a single statement is invariant over the addition of a lower statement stack. *)
(* Converse to stmt_exec_block *)
Theorem stmt_exec_lemma:
!ctx ascope g_scope1 g_scope2 g_scope1' g_scope2' funn stmt stmt' stmts scope_list scope_list'.
stmt_exec (ctx:'a ctx)
          (ascope,[g_scope1; g_scope2],[(funn,[stmt],scope_list)],
           status_running) =
 SOME (ascope,[g_scope1'; g_scope2'],[(funn,[stmt'],scope_list')],status_running) ==>
stmt_exec (ctx:'a ctx)
               (ascope,[g_scope1; g_scope2],[(funn,stmt::stmts,scope_list)],
                status_running) =
 SOME (ascope,[g_scope1'; g_scope2'],[(funn,stmt'::stmts,scope_list')],status_running)
Proof
Induct_on ‘stmt’ >- (
 rpt strip_tac >>
 Cases_on ‘scope_list’ >> (
  fs[stmt_exec_def]
 )
) >> (
 rpt strip_tac >>
 PairCases_on ‘ctx’
) >- (
 fs[exec_stmt_ass_SOME_REWRS]
) >- (
 fs[exec_stmt_cond_SOME_REWRS]
) >- (
 fs[exec_stmt_block_SOME_REWRS]
) >- (
 fs[exec_stmt_ret_SOME_REWRS]
) >- (
 fs[exec_stmt_seq_SOME_REWRS]
) >- (
 fs[exec_stmt_trans_SOME_REWRS]
) >- (
 fs[exec_stmt_app_SOME_REWRS]
) >- (
 fs[exec_stmt_ext_SOME_REWRS]
)
QED

(* Then, define an executable semantics which performs execution until out of fuel. *)
(* Note that all concrete operations remain the same *)
(* Note that expression multi-step execution makes little sense with the current semantics... *)
Definition stmt_multi_exec_def:
 (stmt_multi_exec _ state 0 =
  SOME state)
 /\
 (stmt_multi_exec ctx state (SUC fuel) =
  case stmt_exec ctx state of
  | SOME state' => stmt_multi_exec ctx state' fuel
  | NONE => NONE)
End

(**************************)
(*  Frame list semantics  *)
(**************************)

Definition scopes_to_pass_exec_def:
 scopes_to_pass_exec (funn:funn) (func_map_g:func_map) (b_func_map:b_func_map) (g_scope_list:g_scope_list) =
  case g_scope_list of
  | [block_scope; global_scope] =>
   (case funn of
    | (funn_name x) =>
     (case ALOOKUP b_func_map x of
      | SOME (stmt, x_d_l) => SOME [block_scope; global_scope]
      | NONE =>
       (case ALOOKUP func_map_g x of
        | SOME (stmt, x_d_l) => SOME ([[]; global_scope])
        | NONE => SOME [block_scope; global_scope]))
    | _ => SOME ([[]; global_scope]))
  | _ => NONE
End

Definition scopes_to_retrieve_exec_def:
 scopes_to_retrieve_exec (funn:funn) (func_map_g:func_map) (b_func_map:b_func_map) (g_scope_list_og:g_scope_list) (g_scope_list:g_scope_list) =
  case g_scope_list_og of
   | [block_scope_og; global_scope_og] =>
    (case g_scope_list of
     | [block_scope; global_scope] =>
      (case funn of
       | (funn_name x) =>
        (case ALOOKUP b_func_map x of
         | SOME (stmt, x_d_l) => SOME [block_scope; global_scope]
         | NONE =>
          (case ALOOKUP func_map_g x of
           | SOME (stmt, x_d_l) => SOME [block_scope_og; global_scope]
           | NONE => SOME [block_scope; global_scope]))
       | _ => SOME [block_scope_og; global_scope])
     | _ => NONE)
   | _ => NONE
End

Definition update_return_frame_exec_def:
 update_return_frame_exec xlist dlist ss ss_curr = 
  FOLDL
   (\ss_temp_opt (x,d).
    if (is_d_none_in d)
    then ss_temp_opt
    else
     case ss_temp_opt of
     | SOME ss_temp =>
      (case lookup_map ss_curr (varn_name x) of
       | SOME (v, stret_opt) =>
        (case stret_opt of
         | SOME stret => assign' ss_temp v stret
         | NONE => NONE)
       | _ => NONE)
     | NONE => NONE
   )
   (SOME ss)
   (ZIP(xlist, dlist))
End

Definition copyout_exec_def:
 copyout_exec xlist dlist gsl ss ss_curr =
  if ss_curr <> []
  then
   (case update_return_frame_exec xlist dlist (ss++gsl) [LAST ss_curr] of
    | SOME updated_return_ss =>
     let i = LENGTH updated_return_ss in
     if i >= 2
     then SOME (DROP (i-2) updated_return_ss, TAKE (i-2) updated_return_ss)
     else NONE
    | NONE => NONE)
  else NONE
End

Definition frames_exec_def:
 (******************************************)
 (* Catch-all clauses for special statuses *)
 (frames_exec (ctx:'a ctx) ((ascope:'a, g_scope_list:g_scope_list, frame_list:frame_list, status_returnv v):'a p4$state) = NONE)
  /\
 (frames_exec _ (_, _, _, status_trans x) = NONE)
  /\
 (* Empty frame list *)
 (frames_exec _ (_, _, [], _) = NONE)
  /\
 (*********)
 (* Comp2 + Comp1 case of multiple frames *)
 (frames_exec (apply_table_f, ext_map, func_map, b_func_map, pars_map, tbl_map) (ascope, g_scope_list, ((funn, stmt_stack, scope_list)::((funn', stmt_stack', scope_list')::frame_list'')), status_running) =
  (case scopes_to_pass_exec funn func_map b_func_map g_scope_list of
   | SOME g_scope_list' =>
    (case map_to_pass funn b_func_map of
     | SOME b_func_map' =>
      (case tbl_to_pass funn b_func_map tbl_map of
       | SOME tbl_map' =>
        (case stmt_exec (apply_table_f, ext_map, func_map, b_func_map', pars_map, tbl_map') (ascope, g_scope_list', [(funn, stmt_stack, scope_list)], status_running) of
         | SOME (ascope', g_scope_list'', frame_list', status') =>
          (case status' of
           | status_returnv v =>
            (* Comp2 *)
            (case frame_list' of
             | [(funn, stmt_stack'', scope_list'')] =>
              (case assign' g_scope_list'' v (lval_varname (varn_star funn)) of
               | SOME g_scope_list''' =>
                (case scopes_to_retrieve_exec funn func_map b_func_map g_scope_list g_scope_list''' of
                 | SOME g_scope_list'''' =>
                  (case lookup_funn_sig_body funn func_map b_func_map ext_map of
                   | SOME (stmt'', x_d_l) =>
                    (case scopes_to_pass_exec funn' func_map b_func_map g_scope_list'''' of
                     | SOME g_scope_list''''' =>
                      (case copyout_exec (MAP FST x_d_l) (MAP SND x_d_l) g_scope_list''''' scope_list' scope_list'' of
                       | SOME (g_scope_list'''''', scope_list''') =>
                        (case scopes_to_retrieve_exec funn' func_map b_func_map g_scope_list'''' g_scope_list'''''' of
                         | SOME g_scope_list''''''' =>
                          SOME (ascope', g_scope_list''''''', ((funn', stmt_stack', scope_list''')::frame_list''), status_running)
                         | _ => NONE)
                       | _ => NONE)
                     | _ => NONE)
                   | _ => NONE)
                 | _ => NONE)
               | NONE => NONE)
             | _ => NONE)
           | _ => 
            (* Comp1 *)
            (case scopes_to_retrieve_exec funn func_map b_func_map g_scope_list g_scope_list'' of
             | SOME g_scope_list''' =>
              SOME (ascope', g_scope_list''', frame_list'++((funn', stmt_stack', scope_list')::frame_list''), status')
             | _ => NONE))
         | _ => NONE)
       | _ => NONE)
     | _ => NONE)
   | _ => NONE))
  /\
 (*********)
 (* Comp1, remaining cases *)
 (frames_exec (apply_table_f, ext_map, func_map, b_func_map, pars_map, tbl_map) (ascope, g_scope_list, [(funn, stmt_stack, scope_list)], status_running) =
  (case scopes_to_pass_exec funn func_map b_func_map g_scope_list of
   | SOME g_scope_list' =>
    (case map_to_pass funn b_func_map of
     | SOME b_func_map' =>
      (case tbl_to_pass funn b_func_map tbl_map of
       | SOME tbl_map' =>
        (case stmt_exec (apply_table_f, ext_map, func_map, b_func_map', pars_map, tbl_map') (ascope, g_scope_list', [(funn, stmt_stack, scope_list)], status_running) of
         | SOME (ascope', g_scope_list'', frame_list', status') =>
          (case scopes_to_retrieve_exec funn func_map b_func_map g_scope_list g_scope_list'' of
           | SOME g_scope_list''' =>
            SOME (ascope', g_scope_list''', frame_list', status')
           | _ => NONE)
         | _ => NONE)
       | _ => NONE)
     | _ => NONE)
   | _ => NONE))
 /\
 (frames_exec _ _ = NONE)
End

(***********************************)
(*  Architectural-level semantics  *)
(***********************************)

Definition state_fin_exec_def:
 state_fin_exec status frame_list =
  case frame_list of
  | [(funn, [stmt_empty], scope_list)] =>
   (case status of
    | status_trans x =>
     if x = "accept" \/ x = "reject"
     then T
     else F
    | _ => T)
  | _ =>
   (case status of
    | status_returnv v => T
    | status_trans x =>
     if x = "accept" \/ x = "reject"
     then T
     else F
    | _ => F)
End

Theorem state_fin_exec_equiv:
!status frame_list:frame_list.
 state_fin_exec status frame_list <=> state_fin status frame_list
Proof
fs [state_fin_def, state_fin_exec_def] >>
Cases_on `frame_list` >> (
 fs []
) >- (
 Cases_on `status` >> (
  fs []
 )
) >>
Cases_on `t` >> (
 fs []
) >- (
 PairCases_on `h` >>
 fs [] >>
 Cases_on `h1` >> (
  fs []
 ) >- (
  Cases_on `status` >> (
   fs []
  )
 ) >>
 Cases_on `h` >> (
  fs []
 ) >- (
  Cases_on `t` >> (
   fs []
  ) >> (
   Cases_on `status` >> (
    fs []
   )
  ) >- (
   metis_tac []
  )
 ) >> (
  Cases_on `status` >> (
   fs []
  )
 )
) >>
Cases_on `status` >> (
 fs []
)
QED

(* TODO: Hard-coded to zeroes *)
Definition declare_list_in_scope_exec'_def:
 declare_list_in_scope_exec' (t_scope:t_scope, scope:scope) =
  FOLDR (\(x, (t, lvalop)) f. p4$AUPDATE f (x, (init_v_from_tau_cake t, NONE))) scope t_scope
End

(* TODO: Outsource the stuff that causes too many case splits to other functions
 *       i.e. exec_arch_e, exec_arch_update_return_frame, exec_arch_assign, ... *)
Definition arch_exec_def:
 (arch_exec ((ab_list, pblock_map, ffblock_map, input_f, output_f, copyin_pbl, copyout_pbl, apply_table_f, ext_map, func_map):'a actx)
            (((i, in_out_list, in_out_list', scope):'a aenv), g_scope_list:g_scope_list, arch_frame_list_regular frame_list, status:status) =
  (case oEL i ab_list of
   | SOME (arch_block_pbl x e_l) =>
    (case ALOOKUP pblock_map x of
     | SOME (pbl_type, x_d_list, b_func_map, decl_list, pars_map, tbl_map) =>
      if state_fin_exec status frame_list
      then
       (case lookup_block_body x b_func_map of
        | SOME stmt =>
         (* TODO: The below LENGTH check is only used for proofs (e.g. soundness proof) *)
         (if LENGTH e_l = LENGTH x_d_list
          then
           (* pbl_ret *)
           (* TODO: OK to only copy out from block-global scope here? *)
           (case copyout_pbl (g_scope_list, scope, MAP SND x_d_list, MAP FST x_d_list, set_fin_status pbl_type status) of
            | SOME scope' =>
             (case oLASTN 1 g_scope_list of
              | SOME g_scope_sing =>
               SOME ((i+1, in_out_list, in_out_list', scope'), g_scope_sing,
                     arch_frame_list_empty, status_running)
              | NONE => NONE)
            | _ => NONE)
          else NONE)
        | NONE => NONE)
      else
       (case status of
        | status_trans x' =>
         (* parser_trans *)
         (case pbl_type of
          | pbl_type_parser =>
           (case ALOOKUP pars_map x' of
            | SOME stmt' =>
             SOME ((i, in_out_list, in_out_list', scope), g_scope_list, (arch_frame_list_regular [(funn_name x', [stmt'], [ [] ])]), status_running)
            | _ => NONE)
          | _ => NONE)
        | status_running =>
         (* pbl_exec *)
         (case frames_exec (apply_table_f, ext_map, func_map, b_func_map, pars_map, tbl_map) (scope, g_scope_list, frame_list, status) of
          | SOME (scope', g_scope_list', frame_list', status') =>
           SOME ((i, in_out_list, in_out_list', scope'), g_scope_list', (arch_frame_list_regular frame_list'), status')
          | _ => NONE)
        | _ => NONE)
     | _ => NONE)
   | _ => NONE)
 )
 /\
 (arch_exec (ab_list, pblock_map, ffblock_map, input_f, output_f, copyin_pbl, copyout_pbl, apply_table_f, ext_map, func_map)
            ((i, in_out_list, in_out_list', scope), g_scope_list,
             arch_frame_list_empty, status_running) =
  (case oEL i ab_list of
   (* in *)
   | SOME arch_block_inp =>
    (case input_f (in_out_list, scope) of
     | SOME (in_out_list'', scope') => 
      SOME ((i+1, in_out_list'', in_out_list', scope'), g_scope_list, arch_frame_list_empty,
             status_running)
     | NONE => NONE)
   | SOME (arch_block_pbl x e_l) =>
    (case ALOOKUP pblock_map x of
     (* pbl_init *)
     | SOME (pbl_type, x_d_list, b_func_map, decl_list, pars_map, tbl_map) =>
      (case lookup_block_body x b_func_map of
       | SOME stmt =>
        (* TODO: The below LENGTH check is only used for proofs (e.g. soundness proof) *)
        (if LENGTH e_l = LENGTH x_d_list
         then
          (case copyin_pbl ((MAP FST x_d_list), (MAP SND x_d_list), e_l, scope) of
           | SOME scope' =>
            (case oLASTN 1 g_scope_list of
             | SOME [g_scope] =>
              let g_scope_list' = ([declare_list_in_scope_exec' (decl_list, scope')]++[g_scope]) in
               (case initialise_var_stars func_map b_func_map ext_map g_scope_list' of
                | SOME g_scope_list'' =>
                 SOME ((i, in_out_list, in_out_list', scope), g_scope_list'',
                       arch_frame_list_regular [(funn_name x, [stmt], [ [] ])], status_running)
                | NONE => NONE)
             | _ => NONE)
           | _ => NONE)
         else NONE)
       | NONE => NONE)
     | _ => NONE)
   (* ffbl *)
   | SOME (arch_block_ffbl x) =>
    (case ALOOKUP ffblock_map x of
     | SOME (ffblock_ff ff) =>
      (case ff scope of
       | SOME scope' =>
        SOME ((i+1, in_out_list, in_out_list', scope'), g_scope_list, arch_frame_list_empty, status_running)
       | NONE => NONE)
     | NONE => NONE)
   (* out *)
   | SOME arch_block_out =>
    (case output_f (in_out_list', scope) of
     | SOME (in_out_list'', scope') =>
      SOME ((0, in_out_list, in_out_list'', scope'), g_scope_list, arch_frame_list_empty,
            status_running)
     | NONE => NONE)
   | _ => NONE)
 )
/\
(arch_exec _ _ = NONE)
End

(* Fuel-powered multi-step architectural-level executable semantics *)
Definition arch_multi_exec_def:
 (arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) 0 =
  SOME (aenv, g_scope_list, arch_frame_list, status))
  /\
 (arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) (SUC fuel) =
  case arch_exec actx (aenv, g_scope_list, arch_frame_list, status) of
  | SOME (aenv', g_scope_list', arch_frame_list', status') =>
   arch_multi_exec actx (aenv', g_scope_list', arch_frame_list', status') fuel
  | NONE => NONE)
End

(* This slight alteration always returns the last astate *)
(* TODO: Add number of steps taken? *)
Definition arch_multi_exec_total_def:
 (arch_multi_exec_total actx (astate:'a astate) 0 =
   astate)
  /\
 (arch_multi_exec_total actx astate (SUC fuel) =
  case arch_exec actx astate of
  | SOME astate' =>
   arch_multi_exec_total actx astate' fuel
  | NONE => astate)
End

Theorem arch_multi_exec_1:
!actx s s'.
 arch_multi_exec actx s 1 = SOME s' <=> arch_exec actx s = SOME s'
Proof
rpt strip_tac >>
PairCases_on ‘s’ >>
REWRITE_TAC [arithmeticTheory.ONE, arch_multi_exec_def] >>
Cases_on ‘arch_exec actx ((s0,s1,s2,s3),s4,s5,s6)’ >> (
 fs[]
) >>
PairCases_on ‘x’ >>
fs[]
QED

Theorem arch_multi_exec_add:
!actx aenv g_scope_list arch_frame_list status m n.
arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) (m+n) =
 case arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) n of
 | SOME (aenv', g_scope_list', arch_frame_list', status') =>
  arch_multi_exec actx (aenv', g_scope_list', arch_frame_list', status') m
 | NONE => NONE
Proof
Induct_on `n` >- (
 fs [arch_multi_exec_def]
) >>
rpt strip_tac >>
fs [arch_multi_exec_def, arithmeticTheory.ADD_CLAUSES] >>
(* TODO: uninit *)
Cases_on `arch_exec actx (aenv,g_scope_list,arch_frame_list,status)` >> (
 fs []
) >>
PairCases_on `x` >>
fs []
QED

(* TODO: What to call this? Compose? Combine? *)
Theorem arch_multi_exec_comp_1_tl:
!actx aenv g_scope_list arch_frame_list status m aenv' g_scope_list' arch_frame_list' status' aenv'' g_scope_list'' arch_frame_list'' status''.
arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) 1 =
  SOME (aenv', g_scope_list', arch_frame_list', status') ==>
arch_multi_exec actx (aenv', g_scope_list', arch_frame_list', status') m =
  SOME (aenv'', g_scope_list'', arch_frame_list'', status'') ==>
arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) (1+m) =
  SOME (aenv'', g_scope_list'', arch_frame_list'', status'')
Proof
rpt strip_tac >>
FULL_SIMP_TAC pure_ss [Once arithmeticTheory.ADD_COMM] >>
fs [arch_multi_exec_add]
QED

Theorem arch_multi_exec_split_1_tl:
!actx aenv g_scope_list arch_frame_list status m aenv'' g_scope_list'' arch_frame_list'' status''.
arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) (m+1) =
  SOME (aenv'', g_scope_list'', arch_frame_list'', status'') ==>
(?aenv' g_scope_list' arch_frame_list' status'.
 arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) m =
   SOME (aenv', g_scope_list', arch_frame_list', status') ==>
 arch_multi_exec actx (aenv', g_scope_list', arch_frame_list', status') 1 =
   SOME (aenv'', g_scope_list'', arch_frame_list'', status''))
Proof
rpt strip_tac >>
FULL_SIMP_TAC pure_ss [Once arithmeticTheory.ADD_COMM] >>
fs [arch_multi_exec_add] >>
Cases_on `arch_multi_exec actx (aenv,g_scope_list,arch_frame_list,status) m` >> (
 fs []
) >>
PairCases_on `x` >>
qexistsl_tac [`(x0,x1,x2,x3)`, `x4`, `x5`, `x6`] >>
fs []
QED

Theorem arch_multi_exec_comp_n_tl:
!n m actx assl aenv g_scope_list arch_frame_list status aenv' g_scope_list' arch_frame_list' status' aenv'' g_scope_list'' arch_frame_list'' status''.
arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) n =
  SOME (aenv', g_scope_list', arch_frame_list', status') ==>
arch_multi_exec actx (aenv', g_scope_list', arch_frame_list', status') m =
  SOME (aenv'', g_scope_list'', arch_frame_list'', status'') ==>
arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) (n+m) =
  SOME (aenv'', g_scope_list'', arch_frame_list'', status'')
Proof
rpt strip_tac >>
gs[] >>
fs [arch_multi_exec_add]
QED

(* TODO: use only this shape... *)
Theorem arch_multi_exec_comp_n_tl_alt:
!n m actx s s' s''.
arch_multi_exec actx s n =
  SOME s' ==>
arch_multi_exec actx s' m =
  SOME s'' ==>
arch_multi_exec actx s (n+m) =
  SOME s''
Proof
rpt strip_tac >>
gs[] >>
PairCases_on ‘s’ >>
PairCases_on ‘s'’ >>
PairCases_on ‘s''’ >>
fs [arch_multi_exec_add]
QED

Theorem arch_multi_exec_comp_1_tl_assl:
!m actx assl aenv g_scope_list arch_frame_list status aenv' g_scope_list' arch_frame_list' status' aenv'' g_scope_list'' arch_frame_list'' status''.
(assl ==> arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) 1 =
  SOME (aenv', g_scope_list', arch_frame_list', status')) ==>
(assl ==> arch_multi_exec actx (aenv', g_scope_list', arch_frame_list', status') m =
  SOME (aenv'', g_scope_list'', arch_frame_list'', status'')) ==>
(assl ==> arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) (1+m) =
  SOME (aenv'', g_scope_list'', arch_frame_list'', status''))
Proof
metis_tac[arch_multi_exec_comp_1_tl]
QED

Theorem arch_multi_exec_comp_n_tl_assl:
!n m actx assl aenv g_scope_list arch_frame_list status aenv' g_scope_list' arch_frame_list' status' aenv'' g_scope_list'' arch_frame_list'' status''.
(assl ==> arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) n =
  SOME (aenv', g_scope_list', arch_frame_list', status')) ==>
(assl ==> arch_multi_exec actx (aenv', g_scope_list', arch_frame_list', status') m =
  SOME (aenv'', g_scope_list'', arch_frame_list'', status'')) ==>
(assl ==> arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) (n+m) =
  SOME (aenv'', g_scope_list'', arch_frame_list'', status''))
Proof
rpt strip_tac >>
gs [] >>
fs [arch_multi_exec_add]
QED

Theorem arch_multi_exec_comp_n_tl_assl_conj:
!n m actx assl aenv g_scope_list arch_frame_list status aenv' g_scope_list' arch_frame_list' status' aenv'' g_scope_list'' arch_frame_list'' status''.
((assl ==> arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) n =
  SOME (aenv', g_scope_list', arch_frame_list', status')) /\
 (assl ==> arch_multi_exec actx (aenv', g_scope_list', arch_frame_list', status') m =
  SOME (aenv'', g_scope_list'', arch_frame_list'', status''))) ==>
(assl ==> arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) (n+m) =
  SOME (aenv'', g_scope_list'', arch_frame_list'', status''))
Proof
metis_tac[arch_multi_exec_comp_n_tl_assl]
QED

Theorem arch_multi_exec_comp_n_tl_assl_conj_nomidassl:
!n m actx assl aenv g_scope_list arch_frame_list status aenv' g_scope_list' arch_frame_list' status' aenv'' g_scope_list'' arch_frame_list'' status''.
((assl ==> arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) n =
  SOME (aenv', g_scope_list', arch_frame_list', status')) /\
 (arch_multi_exec actx (aenv', g_scope_list', arch_frame_list', status') m =
  SOME (aenv'', g_scope_list'', arch_frame_list'', status''))) ==>
(assl ==> arch_multi_exec actx (aenv, g_scope_list, arch_frame_list, status) (n+m) =
  SOME (aenv'', g_scope_list'', arch_frame_list'', status''))
Proof
metis_tac[arch_multi_exec_comp_n_tl_assl_conj]
QED

Theorem arch_multi_exec_arch_frame_list_regular:
!ab_list pblock_map ffblock_map input_f output_f copyin_pbl
 copyout_pbl apply_table_f ext_map func_map aenv g_scope_list g_scope_list' arch_frame_list frame_list' n i io_list io_list' ascope.
arch_multi_exec (ab_list,pblock_map,ffblock_map,input_f,output_f,copyin_pbl,
        copyout_pbl,apply_table_f,ext_map,func_map)
          (aenv,g_scope_list,arch_frame_list,
           status_running) (SUC n) =
        SOME
          ((i,io_list,io_list',ascope),g_scope_list',
           arch_frame_list_regular frame_list',status_running) ==>
?x el pbl_type x_d_list b_func_map decl_list pars_map tbl_map.
 EL i ab_list = arch_block_pbl x el /\
 ALOOKUP pblock_map x =
          SOME (pbl_type,x_d_list,b_func_map,decl_list,pars_map,tbl_map)
Proof
rpt strip_tac >>
fs[SUC_ADD_ONE] >>
FULL_SIMP_TAC pure_ss [Once arithmeticTheory.ADD_SYM] >>
fs[arch_multi_exec_add] >>
Cases_on ‘arch_multi_exec
             (ab_list,pblock_map,ffblock_map,input_f,output_f,copyin_pbl,
              copyout_pbl,apply_table_f,ext_map,func_map)
             (aenv,g_scope_list,arch_frame_list,
              status_running) n’ >> (
 fs[]
) >>
PairCases_on ‘x’ >>
fs[] >>
FULL_SIMP_TAC pure_ss [Once arithmeticTheory.ONE] >>
fs[arch_multi_exec_def, AllCaseEqs()] >>
Cases_on ‘x5’ >- (
 Cases_on ‘x6’ >> (
  fs[arch_exec_def]
 ) >>
 Cases_on ‘oEL x0 ab_list’ >> (
  fs[]
 ) >>
 Cases_on ‘x’ >- (
  Cases_on ‘input_f (x1,x3)’ >> (
   fs[]
  ) >>
  gvs[AllCaseEqs()] >>
  qexistsl_tac [‘s’, ‘l’, ‘v6’, ‘v12’, ‘v16’, ‘v20’] >>
  gs[] >>
  Cases_on ‘v21’ >>
  qexistsl_tac [‘q’, ‘r’] >>
  gvs[listTheory.oEL_EQ_EL]
 ) >- (
  gvs[AllCaseEqs()] >>
  gs[] >>
  Cases_on ‘ALOOKUP pblock_map s’ >> (
   fs[]
  ) >>
  PairCases_on ‘x’ >>
  gvs[AllCaseEqs()] >>
  qexistsl_tac [‘s’, ‘l’, ‘v6’, ‘v12’, ‘v16’, ‘v20’, ‘x4'’, ‘x5’] >>
  gvs[listTheory.oEL_EQ_EL]
 ) >- (
  gs[AllCaseEqs()]
 ) >>
 gs[AllCaseEqs()]
) >>
gvs[arch_exec_def, AllCaseEqs()] >- (
 metis_tac[listTheory.oEL_EQ_EL]
) >>
metis_tac[listTheory.oEL_EQ_EL]
QED

val _ = export_theory ();
