(* generated by Ott 0.34 from: ../ott/p4_types.ott ../ott/p4_sem.ott ../ott/p4.ott *)
(* to compile: Holmake p4Theory.uo   *)
(* for interactive use:
  app load ["pred_setTheory","finite_mapTheory","stringTheory","containerTheory","ottLib"];
*)

open HolKernel boolLib Parse bossLib;
open arithmeticTheory stringTheory containerTheory pred_setTheory listTheory 
  finite_mapTheory;

open bitstringTheory;
open wordsTheory;
open alistTheory;

val _ = new_theory "p4";



Type x = ``:string`` (* string *)
Type b = ``:bool`` (* boolean *)
Type bl = ``:bool list`` (* bit-string *)
Type i = ``:num`` (* natural number *)
Type m = ``:num`` (* indices *)

Type bitv = ``:(bl # num)``

Type boolv = ``:bool``



val _ = Hol_datatype ` 
binop = 
   binop_mul (* multiplication *)
 | binop_div (* division *)
 | binop_mod (* modulo *)
 | binop_add (* addition *)
 | binop_sat_add (* saturating addition *)
 | binop_sub (* subtraction *)
 | binop_sat_sub (* saturating subtraction *)
 | binop_shl (* logical left-shift *)
 | binop_shr (* logical right-shift *)
 | binop_le (* less or equal *)
 | binop_ge (* greater or equal *)
 | binop_lt (* less *)
 | binop_gt (* greater *)
 | binop_neq (* not equal *)
 | binop_eq (* equal *)
 | binop_and (* bitwise and *)
 | binop_xor (* bitwise xor *)
 | binop_or (* bitwise or *)
 | binop_bin_and (* binary and *)
 | binop_bin_or (* binary or *)
`;
val _ = Hol_datatype ` 
cast = 
   cast_unsigned of m (* unsigned cast *)
 | cast_bool (* bool cast *)
`;
val _ = Hol_datatype ` 
unop = 
   unop_neg (* negation *)
 | unop_compl (* bitwise complement *)
 | unop_neg_signed (* signed negation *)
 | unop_un_plus (* unary plus *)
`;



val bitv_bl_unop_def = Define `
  bitv_bl_unop unop (bl, n) = (unop bl, n)
`;

val bitv_cast_def = Define `
  bitv_cast n' (v, n) = (fixwidth n' v, n')
`;

val bool_cast_def = Define `
  bool_cast n' b = (fixwidth n' [b], n')
`;

val to_bool_cast_def = Define `
  to_bool_cast (bl, n) = HD $ REVERSE bl
`;

val id_bool_cast_def = Define `
  id_bool_cast b = b
`;

val bitv_bl_binop_def = Define `
  bitv_bl_binop binop (bl, n) (bl', n') = (fixwidth n (binop bl bl'), n)
`;

val get_word_unop_def = Define `
  (get_word_unop unop_compl = word_1comp) /\
  (get_word_unop unop_neg_signed = word_2comp) /\
  (get_word_unop unop_un_plus = (\w. w))
`;
Definition w2_def:
  w2 w = ((w2v:2 word -> bool list) w,2)
End

Definition w3_def:
  w3 w = ((w2v:3 word -> bool list) w,3)
End

Definition w4_def:
  w4 w = ((w2v:4 word -> bool list) w,4)
End

Definition w5_def:
  w5 w = ((w2v:5 word -> bool list) w,5)
End

Definition w6_def:
  w6 w = ((w2v:6 word -> bool list) w,6)
End

Definition w7_def:
  w7 w = ((w2v:7 word -> bool list) w,7)
End

Definition w8_def:
  w8 w = ((w2v:8 word -> bool list) w,8)
End

Definition w9_def:
  w9 w = ((w2v:9 word -> bool list) w,9)
End

Definition w10_def:
  w10 w = ((w2v:10 word -> bool list) w,10)
End

Definition w11_def:
  w11 w = ((w2v:11 word -> bool list) w,11)
End

Definition w12_def:
  w12 w = ((w2v:12 word -> bool list) w,12)
End

Definition w13_def:
  w13 w = ((w2v:13 word -> bool list) w,13)
End

Definition w14_def:
  w14 w = ((w2v:14 word -> bool list) w,14)
End

Definition w15_def:
  w15 w = ((w2v:15 word -> bool list) w,15)
End

Definition w16_def:
  w16 w = ((w2v:16 word -> bool list) w,16)
End

Definition w17_def:
  w17 w = ((w2v:17 word -> bool list) w,17)
End

Definition w18_def:
  w18 w = ((w2v:18 word -> bool list) w,18)
End

Definition w19_def:
  w19 w = ((w2v:19 word -> bool list) w,19)
End

Definition w20_def:
  w20 w = ((w2v:20 word -> bool list) w,20)
End

Definition w21_def:
  w21 w = ((w2v:21 word -> bool list) w,21)
End

Definition w22_def:
  w22 w = ((w2v:22 word -> bool list) w,22)
End

Definition w23_def:
  w23 w = ((w2v:23 word -> bool list) w,23)
End

Definition w24_def:
  w24 w = ((w2v:24 word -> bool list) w,24)
End

Definition w25_def:
  w25 w = ((w2v:25 word -> bool list) w,25)
End

Definition w26_def:
  w26 w = ((w2v:26 word -> bool list) w,26)
End

Definition w27_def:
  w27 w = ((w2v:27 word -> bool list) w,27)
End

Definition w28_def:
  w28 w = ((w2v:28 word -> bool list) w,28)
End

Definition w29_def:
  w29 w = ((w2v:29 word -> bool list) w,29)
End

Definition w30_def:
  w30 w = ((w2v:30 word -> bool list) w,30)
End

Definition w31_def:
  w31 w = ((w2v:31 word -> bool list) w,31)
End

Definition w32_def:
  w32 w = ((w2v:32 word -> bool list) w,32)
End

Definition w33_def:
  w33 w = ((w2v:33 word -> bool list) w,33)
End

Definition w34_def:
  w34 w = ((w2v:34 word -> bool list) w,34)
End

Definition w35_def:
  w35 w = ((w2v:35 word -> bool list) w,35)
End

Definition w36_def:
  w36 w = ((w2v:36 word -> bool list) w,36)
End

Definition w37_def:
  w37 w = ((w2v:37 word -> bool list) w,37)
End

Definition w38_def:
  w38 w = ((w2v:38 word -> bool list) w,38)
End

Definition w39_def:
  w39 w = ((w2v:39 word -> bool list) w,39)
End

Definition w40_def:
  w40 w = ((w2v:40 word -> bool list) w,40)
End

Definition w41_def:
  w41 w = ((w2v:41 word -> bool list) w,41)
End

Definition w42_def:
  w42 w = ((w2v:42 word -> bool list) w,42)
End

Definition w43_def:
  w43 w = ((w2v:43 word -> bool list) w,43)
End

Definition w44_def:
  w44 w = ((w2v:44 word -> bool list) w,44)
End

Definition w45_def:
  w45 w = ((w2v:45 word -> bool list) w,45)
End

Definition w46_def:
  w46 w = ((w2v:46 word -> bool list) w,46)
End

Definition w47_def:
  w47 w = ((w2v:47 word -> bool list) w,47)
End

Definition w48_def:
  w48 w = ((w2v:48 word -> bool list) w,48)
End

Definition w49_def:
  w49 w = ((w2v:49 word -> bool list) w,49)
End

Definition w50_def:
  w50 w = ((w2v:50 word -> bool list) w,50)
End

Definition w51_def:
  w51 w = ((w2v:51 word -> bool list) w,51)
End

Definition w52_def:
  w52 w = ((w2v:52 word -> bool list) w,52)
End

Definition w53_def:
  w53 w = ((w2v:53 word -> bool list) w,53)
End

Definition w54_def:
  w54 w = ((w2v:54 word -> bool list) w,54)
End

Definition w55_def:
  w55 w = ((w2v:55 word -> bool list) w,55)
End

Definition w56_def:
  w56 w = ((w2v:56 word -> bool list) w,56)
End

Definition w57_def:
  w57 w = ((w2v:57 word -> bool list) w,57)
End

Definition w58_def:
  w58 w = ((w2v:58 word -> bool list) w,58)
End

Definition w59_def:
  w59 w = ((w2v:59 word -> bool list) w,59)
End

Definition w60_def:
  w60 w = ((w2v:60 word -> bool list) w,60)
End

Definition w61_def:
  w61 w = ((w2v:61 word -> bool list) w,61)
End

Definition w62_def:
  w62 w = ((w2v:62 word -> bool list) w,62)
End

Definition w63_def:
  w63 w = ((w2v:63 word -> bool list) w,63)
End

Definition w64_def:
  w64 w = ((w2v:64 word -> bool list) w,64)
End

Definition w65_def:
  w65 w = ((w2v:65 word -> bool list) w,65)
End

Definition w66_def:
  w66 w = ((w2v:66 word -> bool list) w,66)
End

Definition w67_def:
  w67 w = ((w2v:67 word -> bool list) w,67)
End

Definition w68_def:
  w68 w = ((w2v:68 word -> bool list) w,68)
End

Definition w69_def:
  w69 w = ((w2v:69 word -> bool list) w,69)
End

Definition w70_def:
  w70 w = ((w2v:70 word -> bool list) w,70)
End

Definition w71_def:
  w71 w = ((w2v:71 word -> bool list) w,71)
End

Definition w72_def:
  w72 w = ((w2v:72 word -> bool list) w,72)
End

Definition w73_def:
  w73 w = ((w2v:73 word -> bool list) w,73)
End

Definition w74_def:
  w74 w = ((w2v:74 word -> bool list) w,74)
End

Definition w75_def:
  w75 w = ((w2v:75 word -> bool list) w,75)
End

Definition w76_def:
  w76 w = ((w2v:76 word -> bool list) w,76)
End

Definition w77_def:
  w77 w = ((w2v:77 word -> bool list) w,77)
End

Definition w78_def:
  w78 w = ((w2v:78 word -> bool list) w,78)
End

Definition w79_def:
  w79 w = ((w2v:79 word -> bool list) w,79)
End

Definition w80_def:
  w80 w = ((w2v:80 word -> bool list) w,80)
End

Definition w81_def:
  w81 w = ((w2v:81 word -> bool list) w,81)
End

Definition w82_def:
  w82 w = ((w2v:82 word -> bool list) w,82)
End

Definition w83_def:
  w83 w = ((w2v:83 word -> bool list) w,83)
End

Definition w84_def:
  w84 w = ((w2v:84 word -> bool list) w,84)
End

Definition w85_def:
  w85 w = ((w2v:85 word -> bool list) w,85)
End

Definition w86_def:
  w86 w = ((w2v:86 word -> bool list) w,86)
End

Definition w87_def:
  w87 w = ((w2v:87 word -> bool list) w,87)
End

Definition w88_def:
  w88 w = ((w2v:88 word -> bool list) w,88)
End

Definition w89_def:
  w89 w = ((w2v:89 word -> bool list) w,89)
End

Definition w90_def:
  w90 w = ((w2v:90 word -> bool list) w,90)
End

Definition w91_def:
  w91 w = ((w2v:91 word -> bool list) w,91)
End

Definition w92_def:
  w92 w = ((w2v:92 word -> bool list) w,92)
End

Definition w93_def:
  w93 w = ((w2v:93 word -> bool list) w,93)
End

Definition w94_def:
  w94 w = ((w2v:94 word -> bool list) w,94)
End

Definition w95_def:
  w95 w = ((w2v:95 word -> bool list) w,95)
End

Definition w96_def:
  w96 w = ((w2v:96 word -> bool list) w,96)
End

Definition w97_def:
  w97 w = ((w2v:97 word -> bool list) w,97)
End

Definition w98_def:
  w98 w = ((w2v:98 word -> bool list) w,98)
End

Definition w99_def:
  w99 w = ((w2v:99 word -> bool list) w,99)
End

Definition w100_def:
  w100 w = ((w2v:100 word -> bool list) w,100)
End

Definition w101_def:
  w101 w = ((w2v:101 word -> bool list) w,101)
End

Definition w102_def:
  w102 w = ((w2v:102 word -> bool list) w,102)
End

Definition w103_def:
  w103 w = ((w2v:103 word -> bool list) w,103)
End

Definition w104_def:
  w104 w = ((w2v:104 word -> bool list) w,104)
End

Definition w105_def:
  w105 w = ((w2v:105 word -> bool list) w,105)
End

Definition w106_def:
  w106 w = ((w2v:106 word -> bool list) w,106)
End

Definition w107_def:
  w107 w = ((w2v:107 word -> bool list) w,107)
End

Definition w108_def:
  w108 w = ((w2v:108 word -> bool list) w,108)
End

Definition w109_def:
  w109 w = ((w2v:109 word -> bool list) w,109)
End

Definition w110_def:
  w110 w = ((w2v:110 word -> bool list) w,110)
End

Definition w111_def:
  w111 w = ((w2v:111 word -> bool list) w,111)
End

Definition w112_def:
  w112 w = ((w2v:112 word -> bool list) w,112)
End

Definition w113_def:
  w113 w = ((w2v:113 word -> bool list) w,113)
End

Definition w114_def:
  w114 w = ((w2v:114 word -> bool list) w,114)
End

Definition w115_def:
  w115 w = ((w2v:115 word -> bool list) w,115)
End

Definition w116_def:
  w116 w = ((w2v:116 word -> bool list) w,116)
End

Definition w117_def:
  w117 w = ((w2v:117 word -> bool list) w,117)
End

Definition w118_def:
  w118 w = ((w2v:118 word -> bool list) w,118)
End

Definition w119_def:
  w119 w = ((w2v:119 word -> bool list) w,119)
End

Definition w120_def:
  w120 w = ((w2v:120 word -> bool list) w,120)
End

Definition w121_def:
  w121 w = ((w2v:121 word -> bool list) w,121)
End

Definition w122_def:
  w122 w = ((w2v:122 word -> bool list) w,122)
End

Definition w123_def:
  w123 w = ((w2v:123 word -> bool list) w,123)
End

Definition w124_def:
  w124 w = ((w2v:124 word -> bool list) w,124)
End

Definition w125_def:
  w125 w = ((w2v:125 word -> bool list) w,125)
End

Definition w126_def:
  w126 w = ((w2v:126 word -> bool list) w,126)
End

Definition w127_def:
  w127 w = ((w2v:127 word -> bool list) w,127)
End

Definition w128_def:
  w128 w = ((w2v:128 word -> bool list) w,128)
End

val bitv_unop_def = Define `
    (bitv_unop unop (v, 1) = (w2v ((get_word_unop unop) ((v2w v): 1 word)), 1) )
/\  (bitv_unop unop (v, 2) = (w2v ((get_word_unop unop) ((v2w v): 2 word)), 2) )
/\  (bitv_unop unop (v, 3) = (w2v ((get_word_unop unop) ((v2w v): 3 word)), 3) )
/\  (bitv_unop unop (v, 4) = (w2v ((get_word_unop unop) ((v2w v): 4 word)), 4) )
/\  (bitv_unop unop (v, 5) = (w2v ((get_word_unop unop) ((v2w v): 5 word)), 5) )
/\  (bitv_unop unop (v, 6) = (w2v ((get_word_unop unop) ((v2w v): 6 word)), 6) )
/\  (bitv_unop unop (v, 7) = (w2v ((get_word_unop unop) ((v2w v): 7 word)), 7) )
/\  (bitv_unop unop (v, 8) = (w2v ((get_word_unop unop) ((v2w v): 8 word)), 8) )
/\  (bitv_unop unop (v, 9) = (w2v ((get_word_unop unop) ((v2w v): 9 word)), 9) )
/\  (bitv_unop unop (v, 10) = (w2v ((get_word_unop unop) ((v2w v): 10 word)), 10) )
/\  (bitv_unop unop (v, 11) = (w2v ((get_word_unop unop) ((v2w v): 11 word)), 11) )
/\  (bitv_unop unop (v, 12) = (w2v ((get_word_unop unop) ((v2w v): 12 word)), 12) )
/\  (bitv_unop unop (v, 13) = (w2v ((get_word_unop unop) ((v2w v): 13 word)), 13) )
/\  (bitv_unop unop (v, 14) = (w2v ((get_word_unop unop) ((v2w v): 14 word)), 14) )
/\  (bitv_unop unop (v, 15) = (w2v ((get_word_unop unop) ((v2w v): 15 word)), 15) )
/\  (bitv_unop unop (v, 16) = (w2v ((get_word_unop unop) ((v2w v): 16 word)), 16) )
/\  (bitv_unop unop (v, 17) = (w2v ((get_word_unop unop) ((v2w v): 17 word)), 17) )
/\  (bitv_unop unop (v, 18) = (w2v ((get_word_unop unop) ((v2w v): 18 word)), 18) )
/\  (bitv_unop unop (v, 19) = (w2v ((get_word_unop unop) ((v2w v): 19 word)), 19) )
/\  (bitv_unop unop (v, 20) = (w2v ((get_word_unop unop) ((v2w v): 20 word)), 20) )
/\  (bitv_unop unop (v, 21) = (w2v ((get_word_unop unop) ((v2w v): 21 word)), 21) )
/\  (bitv_unop unop (v, 22) = (w2v ((get_word_unop unop) ((v2w v): 22 word)), 22) )
/\  (bitv_unop unop (v, 23) = (w2v ((get_word_unop unop) ((v2w v): 23 word)), 23) )
/\  (bitv_unop unop (v, 24) = (w2v ((get_word_unop unop) ((v2w v): 24 word)), 24) )
/\  (bitv_unop unop (v, 25) = (w2v ((get_word_unop unop) ((v2w v): 25 word)), 25) )
/\  (bitv_unop unop (v, 26) = (w2v ((get_word_unop unop) ((v2w v): 26 word)), 26) )
/\  (bitv_unop unop (v, 27) = (w2v ((get_word_unop unop) ((v2w v): 27 word)), 27) )
/\  (bitv_unop unop (v, 28) = (w2v ((get_word_unop unop) ((v2w v): 28 word)), 28) )
/\  (bitv_unop unop (v, 29) = (w2v ((get_word_unop unop) ((v2w v): 29 word)), 29) )
/\  (bitv_unop unop (v, 30) = (w2v ((get_word_unop unop) ((v2w v): 30 word)), 30) )
/\  (bitv_unop unop (v, 31) = (w2v ((get_word_unop unop) ((v2w v): 31 word)), 31) )
/\  (bitv_unop unop (v, 32) = (w2v ((get_word_unop unop) ((v2w v): 32 word)), 32) )
/\  (bitv_unop unop (v, 33) = (w2v ((get_word_unop unop) ((v2w v): 33 word)), 33) )
/\  (bitv_unop unop (v, 34) = (w2v ((get_word_unop unop) ((v2w v): 34 word)), 34) )
/\  (bitv_unop unop (v, 35) = (w2v ((get_word_unop unop) ((v2w v): 35 word)), 35) )
/\  (bitv_unop unop (v, 36) = (w2v ((get_word_unop unop) ((v2w v): 36 word)), 36) )
/\  (bitv_unop unop (v, 37) = (w2v ((get_word_unop unop) ((v2w v): 37 word)), 37) )
/\  (bitv_unop unop (v, 38) = (w2v ((get_word_unop unop) ((v2w v): 38 word)), 38) )
/\  (bitv_unop unop (v, 39) = (w2v ((get_word_unop unop) ((v2w v): 39 word)), 39) )
/\  (bitv_unop unop (v, 40) = (w2v ((get_word_unop unop) ((v2w v): 40 word)), 40) )
/\  (bitv_unop unop (v, 41) = (w2v ((get_word_unop unop) ((v2w v): 41 word)), 41) )
/\  (bitv_unop unop (v, 42) = (w2v ((get_word_unop unop) ((v2w v): 42 word)), 42) )
/\  (bitv_unop unop (v, 43) = (w2v ((get_word_unop unop) ((v2w v): 43 word)), 43) )
/\  (bitv_unop unop (v, 44) = (w2v ((get_word_unop unop) ((v2w v): 44 word)), 44) )
/\  (bitv_unop unop (v, 45) = (w2v ((get_word_unop unop) ((v2w v): 45 word)), 45) )
/\  (bitv_unop unop (v, 46) = (w2v ((get_word_unop unop) ((v2w v): 46 word)), 46) )
/\  (bitv_unop unop (v, 47) = (w2v ((get_word_unop unop) ((v2w v): 47 word)), 47) )
/\  (bitv_unop unop (v, 48) = (w2v ((get_word_unop unop) ((v2w v): 48 word)), 48) )
/\  (bitv_unop unop (v, 49) = (w2v ((get_word_unop unop) ((v2w v): 49 word)), 49) )
/\  (bitv_unop unop (v, 50) = (w2v ((get_word_unop unop) ((v2w v): 50 word)), 50) )
/\  (bitv_unop unop (v, 51) = (w2v ((get_word_unop unop) ((v2w v): 51 word)), 51) )
/\  (bitv_unop unop (v, 52) = (w2v ((get_word_unop unop) ((v2w v): 52 word)), 52) )
/\  (bitv_unop unop (v, 53) = (w2v ((get_word_unop unop) ((v2w v): 53 word)), 53) )
/\  (bitv_unop unop (v, 54) = (w2v ((get_word_unop unop) ((v2w v): 54 word)), 54) )
/\  (bitv_unop unop (v, 55) = (w2v ((get_word_unop unop) ((v2w v): 55 word)), 55) )
/\  (bitv_unop unop (v, 56) = (w2v ((get_word_unop unop) ((v2w v): 56 word)), 56) )
/\  (bitv_unop unop (v, 57) = (w2v ((get_word_unop unop) ((v2w v): 57 word)), 57) )
/\  (bitv_unop unop (v, 58) = (w2v ((get_word_unop unop) ((v2w v): 58 word)), 58) )
/\  (bitv_unop unop (v, 59) = (w2v ((get_word_unop unop) ((v2w v): 59 word)), 59) )
/\  (bitv_unop unop (v, 60) = (w2v ((get_word_unop unop) ((v2w v): 60 word)), 60) )
/\  (bitv_unop unop (v, 61) = (w2v ((get_word_unop unop) ((v2w v): 61 word)), 61) )
/\  (bitv_unop unop (v, 62) = (w2v ((get_word_unop unop) ((v2w v): 62 word)), 62) )
/\  (bitv_unop unop (v, 63) = (w2v ((get_word_unop unop) ((v2w v): 63 word)), 63) )
/\  (bitv_unop unop (v, 64) = (w2v ((get_word_unop unop) ((v2w v): 64 word)), 64) )
/\  (bitv_unop unop (v, 65) = (w2v ((get_word_unop unop) ((v2w v): 65 word)), 65) )
/\  (bitv_unop unop (v, 66) = (w2v ((get_word_unop unop) ((v2w v): 66 word)), 66) )
/\  (bitv_unop unop (v, 67) = (w2v ((get_word_unop unop) ((v2w v): 67 word)), 67) )
/\  (bitv_unop unop (v, 68) = (w2v ((get_word_unop unop) ((v2w v): 68 word)), 68) )
/\  (bitv_unop unop (v, 69) = (w2v ((get_word_unop unop) ((v2w v): 69 word)), 69) )
/\  (bitv_unop unop (v, 70) = (w2v ((get_word_unop unop) ((v2w v): 70 word)), 70) )
/\  (bitv_unop unop (v, 71) = (w2v ((get_word_unop unop) ((v2w v): 71 word)), 71) )
/\  (bitv_unop unop (v, 72) = (w2v ((get_word_unop unop) ((v2w v): 72 word)), 72) )
/\  (bitv_unop unop (v, 73) = (w2v ((get_word_unop unop) ((v2w v): 73 word)), 73) )
/\  (bitv_unop unop (v, 74) = (w2v ((get_word_unop unop) ((v2w v): 74 word)), 74) )
/\  (bitv_unop unop (v, 75) = (w2v ((get_word_unop unop) ((v2w v): 75 word)), 75) )
/\  (bitv_unop unop (v, 76) = (w2v ((get_word_unop unop) ((v2w v): 76 word)), 76) )
/\  (bitv_unop unop (v, 77) = (w2v ((get_word_unop unop) ((v2w v): 77 word)), 77) )
/\  (bitv_unop unop (v, 78) = (w2v ((get_word_unop unop) ((v2w v): 78 word)), 78) )
/\  (bitv_unop unop (v, 79) = (w2v ((get_word_unop unop) ((v2w v): 79 word)), 79) )
/\  (bitv_unop unop (v, 80) = (w2v ((get_word_unop unop) ((v2w v): 80 word)), 80) )
/\  (bitv_unop unop (v, 81) = (w2v ((get_word_unop unop) ((v2w v): 81 word)), 81) )
/\  (bitv_unop unop (v, 82) = (w2v ((get_word_unop unop) ((v2w v): 82 word)), 82) )
/\  (bitv_unop unop (v, 83) = (w2v ((get_word_unop unop) ((v2w v): 83 word)), 83) )
/\  (bitv_unop unop (v, 84) = (w2v ((get_word_unop unop) ((v2w v): 84 word)), 84) )
/\  (bitv_unop unop (v, 85) = (w2v ((get_word_unop unop) ((v2w v): 85 word)), 85) )
/\  (bitv_unop unop (v, 86) = (w2v ((get_word_unop unop) ((v2w v): 86 word)), 86) )
/\  (bitv_unop unop (v, 87) = (w2v ((get_word_unop unop) ((v2w v): 87 word)), 87) )
/\  (bitv_unop unop (v, 88) = (w2v ((get_word_unop unop) ((v2w v): 88 word)), 88) )
/\  (bitv_unop unop (v, 89) = (w2v ((get_word_unop unop) ((v2w v): 89 word)), 89) )
/\  (bitv_unop unop (v, 90) = (w2v ((get_word_unop unop) ((v2w v): 90 word)), 90) )
/\  (bitv_unop unop (v, 91) = (w2v ((get_word_unop unop) ((v2w v): 91 word)), 91) )
/\  (bitv_unop unop (v, 92) = (w2v ((get_word_unop unop) ((v2w v): 92 word)), 92) )
/\  (bitv_unop unop (v, 93) = (w2v ((get_word_unop unop) ((v2w v): 93 word)), 93) )
/\  (bitv_unop unop (v, 94) = (w2v ((get_word_unop unop) ((v2w v): 94 word)), 94) )
/\  (bitv_unop unop (v, 95) = (w2v ((get_word_unop unop) ((v2w v): 95 word)), 95) )
/\  (bitv_unop unop (v, 96) = (w2v ((get_word_unop unop) ((v2w v): 96 word)), 96) )
/\  (bitv_unop unop (v, 97) = (w2v ((get_word_unop unop) ((v2w v): 97 word)), 97) )
/\  (bitv_unop unop (v, 98) = (w2v ((get_word_unop unop) ((v2w v): 98 word)), 98) )
/\  (bitv_unop unop (v, 99) = (w2v ((get_word_unop unop) ((v2w v): 99 word)), 99) )
/\  (bitv_unop unop (v, 100) = (w2v ((get_word_unop unop) ((v2w v): 100 word)), 100) )
/\  (bitv_unop unop (v, 101) = (w2v ((get_word_unop unop) ((v2w v): 101 word)), 101) )
/\  (bitv_unop unop (v, 102) = (w2v ((get_word_unop unop) ((v2w v): 102 word)), 102) )
/\  (bitv_unop unop (v, 103) = (w2v ((get_word_unop unop) ((v2w v): 103 word)), 103) )
/\  (bitv_unop unop (v, 104) = (w2v ((get_word_unop unop) ((v2w v): 104 word)), 104) )
/\  (bitv_unop unop (v, 105) = (w2v ((get_word_unop unop) ((v2w v): 105 word)), 105) )
/\  (bitv_unop unop (v, 106) = (w2v ((get_word_unop unop) ((v2w v): 106 word)), 106) )
/\  (bitv_unop unop (v, 107) = (w2v ((get_word_unop unop) ((v2w v): 107 word)), 107) )
/\  (bitv_unop unop (v, 108) = (w2v ((get_word_unop unop) ((v2w v): 108 word)), 108) )
/\  (bitv_unop unop (v, 109) = (w2v ((get_word_unop unop) ((v2w v): 109 word)), 109) )
/\  (bitv_unop unop (v, 110) = (w2v ((get_word_unop unop) ((v2w v): 110 word)), 110) )
/\  (bitv_unop unop (v, 111) = (w2v ((get_word_unop unop) ((v2w v): 111 word)), 111) )
/\  (bitv_unop unop (v, 112) = (w2v ((get_word_unop unop) ((v2w v): 112 word)), 112) )
/\  (bitv_unop unop (v, 113) = (w2v ((get_word_unop unop) ((v2w v): 113 word)), 113) )
/\  (bitv_unop unop (v, 114) = (w2v ((get_word_unop unop) ((v2w v): 114 word)), 114) )
/\  (bitv_unop unop (v, 115) = (w2v ((get_word_unop unop) ((v2w v): 115 word)), 115) )
/\  (bitv_unop unop (v, 116) = (w2v ((get_word_unop unop) ((v2w v): 116 word)), 116) )
/\  (bitv_unop unop (v, 117) = (w2v ((get_word_unop unop) ((v2w v): 117 word)), 117) )
/\  (bitv_unop unop (v, 118) = (w2v ((get_word_unop unop) ((v2w v): 118 word)), 118) )
/\  (bitv_unop unop (v, 119) = (w2v ((get_word_unop unop) ((v2w v): 119 word)), 119) )
/\  (bitv_unop unop (v, 120) = (w2v ((get_word_unop unop) ((v2w v): 120 word)), 120) )
/\  (bitv_unop unop (v, 121) = (w2v ((get_word_unop unop) ((v2w v): 121 word)), 121) )
/\  (bitv_unop unop (v, 122) = (w2v ((get_word_unop unop) ((v2w v): 122 word)), 122) )
/\  (bitv_unop unop (v, 123) = (w2v ((get_word_unop unop) ((v2w v): 123 word)), 123) )
/\  (bitv_unop unop (v, 124) = (w2v ((get_word_unop unop) ((v2w v): 124 word)), 124) )
/\  (bitv_unop unop (v, 125) = (w2v ((get_word_unop unop) ((v2w v): 125 word)), 125) )
/\  (bitv_unop unop (v, 126) = (w2v ((get_word_unop unop) ((v2w v): 126 word)), 126) )
/\  (bitv_unop unop (v, 127) = (w2v ((get_word_unop unop) ((v2w v): 127 word)), 127) )
/\  (bitv_unop unop (v, 128) = (w2v ((get_word_unop unop) ((v2w v): 128 word)), 128) )
`;

val get_word_binop_def = Define `
    (get_word_binop binop_mul = word_mul)
/\  (get_word_binop binop_div = word_div)
/\  (get_word_binop binop_mod = word_mod)
/\  (get_word_binop binop_add = word_add)
/\  (get_word_binop binop_sat_add = saturate_add)
/\  (get_word_binop binop_sub = word_sub)
/\  (get_word_binop binop_sat_sub = saturate_sub)
/\  (get_word_binop binop_shl = word_lsl_bv)
/\  (get_word_binop binop_shr = word_lsr_bv)
/\  (get_word_binop binop_and = word_and)
/\  (get_word_binop binop_xor = word_xor)
/\  (get_word_binop binop_or = word_or)
`;

val bitv_binop_inner_def = Define `
    (bitv_binop_inner binop v v' 1 = SOME (w2v ((get_word_binop binop) ((v2w v): 1 word) ((v2w v'): 1 word)), 1) )
/\  (bitv_binop_inner binop v v' 2 = SOME (w2v ((get_word_binop binop) ((v2w v): 2 word) ((v2w v'): 2 word)), 2) )
/\  (bitv_binop_inner binop v v' 3 = SOME (w2v ((get_word_binop binop) ((v2w v): 3 word) ((v2w v'): 3 word)), 3) )
/\  (bitv_binop_inner binop v v' 4 = SOME (w2v ((get_word_binop binop) ((v2w v): 4 word) ((v2w v'): 4 word)), 4) )
/\  (bitv_binop_inner binop v v' 5 = SOME (w2v ((get_word_binop binop) ((v2w v): 5 word) ((v2w v'): 5 word)), 5) )
/\  (bitv_binop_inner binop v v' 6 = SOME (w2v ((get_word_binop binop) ((v2w v): 6 word) ((v2w v'): 6 word)), 6) )
/\  (bitv_binop_inner binop v v' 7 = SOME (w2v ((get_word_binop binop) ((v2w v): 7 word) ((v2w v'): 7 word)), 7) )
/\  (bitv_binop_inner binop v v' 8 = SOME (w2v ((get_word_binop binop) ((v2w v): 8 word) ((v2w v'): 8 word)), 8) )
/\  (bitv_binop_inner binop v v' 9 = SOME (w2v ((get_word_binop binop) ((v2w v): 9 word) ((v2w v'): 9 word)), 9) )
/\  (bitv_binop_inner binop v v' 10 = SOME (w2v ((get_word_binop binop) ((v2w v): 10 word) ((v2w v'): 10 word)), 10) )
/\  (bitv_binop_inner binop v v' 11 = SOME (w2v ((get_word_binop binop) ((v2w v): 11 word) ((v2w v'): 11 word)), 11) )
/\  (bitv_binop_inner binop v v' 12 = SOME (w2v ((get_word_binop binop) ((v2w v): 12 word) ((v2w v'): 12 word)), 12) )
/\  (bitv_binop_inner binop v v' 13 = SOME (w2v ((get_word_binop binop) ((v2w v): 13 word) ((v2w v'): 13 word)), 13) )
/\  (bitv_binop_inner binop v v' 14 = SOME (w2v ((get_word_binop binop) ((v2w v): 14 word) ((v2w v'): 14 word)), 14) )
/\  (bitv_binop_inner binop v v' 15 = SOME (w2v ((get_word_binop binop) ((v2w v): 15 word) ((v2w v'): 15 word)), 15) )
/\  (bitv_binop_inner binop v v' 16 = SOME (w2v ((get_word_binop binop) ((v2w v): 16 word) ((v2w v'): 16 word)), 16) )
/\  (bitv_binop_inner binop v v' 17 = SOME (w2v ((get_word_binop binop) ((v2w v): 17 word) ((v2w v'): 17 word)), 17) )
/\  (bitv_binop_inner binop v v' 18 = SOME (w2v ((get_word_binop binop) ((v2w v): 18 word) ((v2w v'): 18 word)), 18) )
/\  (bitv_binop_inner binop v v' 19 = SOME (w2v ((get_word_binop binop) ((v2w v): 19 word) ((v2w v'): 19 word)), 19) )
/\  (bitv_binop_inner binop v v' 20 = SOME (w2v ((get_word_binop binop) ((v2w v): 20 word) ((v2w v'): 20 word)), 20) )
/\  (bitv_binop_inner binop v v' 21 = SOME (w2v ((get_word_binop binop) ((v2w v): 21 word) ((v2w v'): 21 word)), 21) )
/\  (bitv_binop_inner binop v v' 22 = SOME (w2v ((get_word_binop binop) ((v2w v): 22 word) ((v2w v'): 22 word)), 22) )
/\  (bitv_binop_inner binop v v' 23 = SOME (w2v ((get_word_binop binop) ((v2w v): 23 word) ((v2w v'): 23 word)), 23) )
/\  (bitv_binop_inner binop v v' 24 = SOME (w2v ((get_word_binop binop) ((v2w v): 24 word) ((v2w v'): 24 word)), 24) )
/\  (bitv_binop_inner binop v v' 25 = SOME (w2v ((get_word_binop binop) ((v2w v): 25 word) ((v2w v'): 25 word)), 25) )
/\  (bitv_binop_inner binop v v' 26 = SOME (w2v ((get_word_binop binop) ((v2w v): 26 word) ((v2w v'): 26 word)), 26) )
/\  (bitv_binop_inner binop v v' 27 = SOME (w2v ((get_word_binop binop) ((v2w v): 27 word) ((v2w v'): 27 word)), 27) )
/\  (bitv_binop_inner binop v v' 28 = SOME (w2v ((get_word_binop binop) ((v2w v): 28 word) ((v2w v'): 28 word)), 28) )
/\  (bitv_binop_inner binop v v' 29 = SOME (w2v ((get_word_binop binop) ((v2w v): 29 word) ((v2w v'): 29 word)), 29) )
/\  (bitv_binop_inner binop v v' 30 = SOME (w2v ((get_word_binop binop) ((v2w v): 30 word) ((v2w v'): 30 word)), 30) )
/\  (bitv_binop_inner binop v v' 31 = SOME (w2v ((get_word_binop binop) ((v2w v): 31 word) ((v2w v'): 31 word)), 31) )
/\  (bitv_binop_inner binop v v' 32 = SOME (w2v ((get_word_binop binop) ((v2w v): 32 word) ((v2w v'): 32 word)), 32) )
/\  (bitv_binop_inner binop v v' 33 = SOME (w2v ((get_word_binop binop) ((v2w v): 33 word) ((v2w v'): 33 word)), 33) )
/\  (bitv_binop_inner binop v v' 34 = SOME (w2v ((get_word_binop binop) ((v2w v): 34 word) ((v2w v'): 34 word)), 34) )
/\  (bitv_binop_inner binop v v' 35 = SOME (w2v ((get_word_binop binop) ((v2w v): 35 word) ((v2w v'): 35 word)), 35) )
/\  (bitv_binop_inner binop v v' 36 = SOME (w2v ((get_word_binop binop) ((v2w v): 36 word) ((v2w v'): 36 word)), 36) )
/\  (bitv_binop_inner binop v v' 37 = SOME (w2v ((get_word_binop binop) ((v2w v): 37 word) ((v2w v'): 37 word)), 37) )
/\  (bitv_binop_inner binop v v' 38 = SOME (w2v ((get_word_binop binop) ((v2w v): 38 word) ((v2w v'): 38 word)), 38) )
/\  (bitv_binop_inner binop v v' 39 = SOME (w2v ((get_word_binop binop) ((v2w v): 39 word) ((v2w v'): 39 word)), 39) )
/\  (bitv_binop_inner binop v v' 40 = SOME (w2v ((get_word_binop binop) ((v2w v): 40 word) ((v2w v'): 40 word)), 40) )
/\  (bitv_binop_inner binop v v' 41 = SOME (w2v ((get_word_binop binop) ((v2w v): 41 word) ((v2w v'): 41 word)), 41) )
/\  (bitv_binop_inner binop v v' 42 = SOME (w2v ((get_word_binop binop) ((v2w v): 42 word) ((v2w v'): 42 word)), 42) )
/\  (bitv_binop_inner binop v v' 43 = SOME (w2v ((get_word_binop binop) ((v2w v): 43 word) ((v2w v'): 43 word)), 43) )
/\  (bitv_binop_inner binop v v' 44 = SOME (w2v ((get_word_binop binop) ((v2w v): 44 word) ((v2w v'): 44 word)), 44) )
/\  (bitv_binop_inner binop v v' 45 = SOME (w2v ((get_word_binop binop) ((v2w v): 45 word) ((v2w v'): 45 word)), 45) )
/\  (bitv_binop_inner binop v v' 46 = SOME (w2v ((get_word_binop binop) ((v2w v): 46 word) ((v2w v'): 46 word)), 46) )
/\  (bitv_binop_inner binop v v' 47 = SOME (w2v ((get_word_binop binop) ((v2w v): 47 word) ((v2w v'): 47 word)), 47) )
/\  (bitv_binop_inner binop v v' 48 = SOME (w2v ((get_word_binop binop) ((v2w v): 48 word) ((v2w v'): 48 word)), 48) )
/\  (bitv_binop_inner binop v v' 49 = SOME (w2v ((get_word_binop binop) ((v2w v): 49 word) ((v2w v'): 49 word)), 49) )
/\  (bitv_binop_inner binop v v' 50 = SOME (w2v ((get_word_binop binop) ((v2w v): 50 word) ((v2w v'): 50 word)), 50) )
/\  (bitv_binop_inner binop v v' 51 = SOME (w2v ((get_word_binop binop) ((v2w v): 51 word) ((v2w v'): 51 word)), 51) )
/\  (bitv_binop_inner binop v v' 52 = SOME (w2v ((get_word_binop binop) ((v2w v): 52 word) ((v2w v'): 52 word)), 52) )
/\  (bitv_binop_inner binop v v' 53 = SOME (w2v ((get_word_binop binop) ((v2w v): 53 word) ((v2w v'): 53 word)), 53) )
/\  (bitv_binop_inner binop v v' 54 = SOME (w2v ((get_word_binop binop) ((v2w v): 54 word) ((v2w v'): 54 word)), 54) )
/\  (bitv_binop_inner binop v v' 55 = SOME (w2v ((get_word_binop binop) ((v2w v): 55 word) ((v2w v'): 55 word)), 55) )
/\  (bitv_binop_inner binop v v' 56 = SOME (w2v ((get_word_binop binop) ((v2w v): 56 word) ((v2w v'): 56 word)), 56) )
/\  (bitv_binop_inner binop v v' 57 = SOME (w2v ((get_word_binop binop) ((v2w v): 57 word) ((v2w v'): 57 word)), 57) )
/\  (bitv_binop_inner binop v v' 58 = SOME (w2v ((get_word_binop binop) ((v2w v): 58 word) ((v2w v'): 58 word)), 58) )
/\  (bitv_binop_inner binop v v' 59 = SOME (w2v ((get_word_binop binop) ((v2w v): 59 word) ((v2w v'): 59 word)), 59) )
/\  (bitv_binop_inner binop v v' 60 = SOME (w2v ((get_word_binop binop) ((v2w v): 60 word) ((v2w v'): 60 word)), 60) )
/\  (bitv_binop_inner binop v v' 61 = SOME (w2v ((get_word_binop binop) ((v2w v): 61 word) ((v2w v'): 61 word)), 61) )
/\  (bitv_binop_inner binop v v' 62 = SOME (w2v ((get_word_binop binop) ((v2w v): 62 word) ((v2w v'): 62 word)), 62) )
/\  (bitv_binop_inner binop v v' 63 = SOME (w2v ((get_word_binop binop) ((v2w v): 63 word) ((v2w v'): 63 word)), 63) )
/\  (bitv_binop_inner binop v v' 64 = SOME (w2v ((get_word_binop binop) ((v2w v): 64 word) ((v2w v'): 64 word)), 64) )
/\  (bitv_binop_inner binop v v' 65 = SOME (w2v ((get_word_binop binop) ((v2w v): 65 word) ((v2w v'): 65 word)), 65) )
/\  (bitv_binop_inner binop v v' 66 = SOME (w2v ((get_word_binop binop) ((v2w v): 66 word) ((v2w v'): 66 word)), 66) )
/\  (bitv_binop_inner binop v v' 67 = SOME (w2v ((get_word_binop binop) ((v2w v): 67 word) ((v2w v'): 67 word)), 67) )
/\  (bitv_binop_inner binop v v' 68 = SOME (w2v ((get_word_binop binop) ((v2w v): 68 word) ((v2w v'): 68 word)), 68) )
/\  (bitv_binop_inner binop v v' 69 = SOME (w2v ((get_word_binop binop) ((v2w v): 69 word) ((v2w v'): 69 word)), 69) )
/\  (bitv_binop_inner binop v v' 70 = SOME (w2v ((get_word_binop binop) ((v2w v): 70 word) ((v2w v'): 70 word)), 70) )
/\  (bitv_binop_inner binop v v' 71 = SOME (w2v ((get_word_binop binop) ((v2w v): 71 word) ((v2w v'): 71 word)), 71) )
/\  (bitv_binop_inner binop v v' 72 = SOME (w2v ((get_word_binop binop) ((v2w v): 72 word) ((v2w v'): 72 word)), 72) )
/\  (bitv_binop_inner binop v v' 73 = SOME (w2v ((get_word_binop binop) ((v2w v): 73 word) ((v2w v'): 73 word)), 73) )
/\  (bitv_binop_inner binop v v' 74 = SOME (w2v ((get_word_binop binop) ((v2w v): 74 word) ((v2w v'): 74 word)), 74) )
/\  (bitv_binop_inner binop v v' 75 = SOME (w2v ((get_word_binop binop) ((v2w v): 75 word) ((v2w v'): 75 word)), 75) )
/\  (bitv_binop_inner binop v v' 76 = SOME (w2v ((get_word_binop binop) ((v2w v): 76 word) ((v2w v'): 76 word)), 76) )
/\  (bitv_binop_inner binop v v' 77 = SOME (w2v ((get_word_binop binop) ((v2w v): 77 word) ((v2w v'): 77 word)), 77) )
/\  (bitv_binop_inner binop v v' 78 = SOME (w2v ((get_word_binop binop) ((v2w v): 78 word) ((v2w v'): 78 word)), 78) )
/\  (bitv_binop_inner binop v v' 79 = SOME (w2v ((get_word_binop binop) ((v2w v): 79 word) ((v2w v'): 79 word)), 79) )
/\  (bitv_binop_inner binop v v' 80 = SOME (w2v ((get_word_binop binop) ((v2w v): 80 word) ((v2w v'): 80 word)), 80) )
/\  (bitv_binop_inner binop v v' 81 = SOME (w2v ((get_word_binop binop) ((v2w v): 81 word) ((v2w v'): 81 word)), 81) )
/\  (bitv_binop_inner binop v v' 82 = SOME (w2v ((get_word_binop binop) ((v2w v): 82 word) ((v2w v'): 82 word)), 82) )
/\  (bitv_binop_inner binop v v' 83 = SOME (w2v ((get_word_binop binop) ((v2w v): 83 word) ((v2w v'): 83 word)), 83) )
/\  (bitv_binop_inner binop v v' 84 = SOME (w2v ((get_word_binop binop) ((v2w v): 84 word) ((v2w v'): 84 word)), 84) )
/\  (bitv_binop_inner binop v v' 85 = SOME (w2v ((get_word_binop binop) ((v2w v): 85 word) ((v2w v'): 85 word)), 85) )
/\  (bitv_binop_inner binop v v' 86 = SOME (w2v ((get_word_binop binop) ((v2w v): 86 word) ((v2w v'): 86 word)), 86) )
/\  (bitv_binop_inner binop v v' 87 = SOME (w2v ((get_word_binop binop) ((v2w v): 87 word) ((v2w v'): 87 word)), 87) )
/\  (bitv_binop_inner binop v v' 88 = SOME (w2v ((get_word_binop binop) ((v2w v): 88 word) ((v2w v'): 88 word)), 88) )
/\  (bitv_binop_inner binop v v' 89 = SOME (w2v ((get_word_binop binop) ((v2w v): 89 word) ((v2w v'): 89 word)), 89) )
/\  (bitv_binop_inner binop v v' 90 = SOME (w2v ((get_word_binop binop) ((v2w v): 90 word) ((v2w v'): 90 word)), 90) )
/\  (bitv_binop_inner binop v v' 91 = SOME (w2v ((get_word_binop binop) ((v2w v): 91 word) ((v2w v'): 91 word)), 91) )
/\  (bitv_binop_inner binop v v' 92 = SOME (w2v ((get_word_binop binop) ((v2w v): 92 word) ((v2w v'): 92 word)), 92) )
/\  (bitv_binop_inner binop v v' 93 = SOME (w2v ((get_word_binop binop) ((v2w v): 93 word) ((v2w v'): 93 word)), 93) )
/\  (bitv_binop_inner binop v v' 94 = SOME (w2v ((get_word_binop binop) ((v2w v): 94 word) ((v2w v'): 94 word)), 94) )
/\  (bitv_binop_inner binop v v' 95 = SOME (w2v ((get_word_binop binop) ((v2w v): 95 word) ((v2w v'): 95 word)), 95) )
/\  (bitv_binop_inner binop v v' 96 = SOME (w2v ((get_word_binop binop) ((v2w v): 96 word) ((v2w v'): 96 word)), 96) )
/\  (bitv_binop_inner binop v v' 97 = SOME (w2v ((get_word_binop binop) ((v2w v): 97 word) ((v2w v'): 97 word)), 97) )
/\  (bitv_binop_inner binop v v' 98 = SOME (w2v ((get_word_binop binop) ((v2w v): 98 word) ((v2w v'): 98 word)), 98) )
/\  (bitv_binop_inner binop v v' 99 = SOME (w2v ((get_word_binop binop) ((v2w v): 99 word) ((v2w v'): 99 word)), 99) )
/\  (bitv_binop_inner binop v v' 100 = SOME (w2v ((get_word_binop binop) ((v2w v): 100 word) ((v2w v'): 100 word)), 100) )
/\  (bitv_binop_inner binop v v' 101 = SOME (w2v ((get_word_binop binop) ((v2w v): 101 word) ((v2w v'): 101 word)), 101) )
/\  (bitv_binop_inner binop v v' 102 = SOME (w2v ((get_word_binop binop) ((v2w v): 102 word) ((v2w v'): 102 word)), 102) )
/\  (bitv_binop_inner binop v v' 103 = SOME (w2v ((get_word_binop binop) ((v2w v): 103 word) ((v2w v'): 103 word)), 103) )
/\  (bitv_binop_inner binop v v' 104 = SOME (w2v ((get_word_binop binop) ((v2w v): 104 word) ((v2w v'): 104 word)), 104) )
/\  (bitv_binop_inner binop v v' 105 = SOME (w2v ((get_word_binop binop) ((v2w v): 105 word) ((v2w v'): 105 word)), 105) )
/\  (bitv_binop_inner binop v v' 106 = SOME (w2v ((get_word_binop binop) ((v2w v): 106 word) ((v2w v'): 106 word)), 106) )
/\  (bitv_binop_inner binop v v' 107 = SOME (w2v ((get_word_binop binop) ((v2w v): 107 word) ((v2w v'): 107 word)), 107) )
/\  (bitv_binop_inner binop v v' 108 = SOME (w2v ((get_word_binop binop) ((v2w v): 108 word) ((v2w v'): 108 word)), 108) )
/\  (bitv_binop_inner binop v v' 109 = SOME (w2v ((get_word_binop binop) ((v2w v): 109 word) ((v2w v'): 109 word)), 109) )
/\  (bitv_binop_inner binop v v' 110 = SOME (w2v ((get_word_binop binop) ((v2w v): 110 word) ((v2w v'): 110 word)), 110) )
/\  (bitv_binop_inner binop v v' 111 = SOME (w2v ((get_word_binop binop) ((v2w v): 111 word) ((v2w v'): 111 word)), 111) )
/\  (bitv_binop_inner binop v v' 112 = SOME (w2v ((get_word_binop binop) ((v2w v): 112 word) ((v2w v'): 112 word)), 112) )
/\  (bitv_binop_inner binop v v' 113 = SOME (w2v ((get_word_binop binop) ((v2w v): 113 word) ((v2w v'): 113 word)), 113) )
/\  (bitv_binop_inner binop v v' 114 = SOME (w2v ((get_word_binop binop) ((v2w v): 114 word) ((v2w v'): 114 word)), 114) )
/\  (bitv_binop_inner binop v v' 115 = SOME (w2v ((get_word_binop binop) ((v2w v): 115 word) ((v2w v'): 115 word)), 115) )
/\  (bitv_binop_inner binop v v' 116 = SOME (w2v ((get_word_binop binop) ((v2w v): 116 word) ((v2w v'): 116 word)), 116) )
/\  (bitv_binop_inner binop v v' 117 = SOME (w2v ((get_word_binop binop) ((v2w v): 117 word) ((v2w v'): 117 word)), 117) )
/\  (bitv_binop_inner binop v v' 118 = SOME (w2v ((get_word_binop binop) ((v2w v): 118 word) ((v2w v'): 118 word)), 118) )
/\  (bitv_binop_inner binop v v' 119 = SOME (w2v ((get_word_binop binop) ((v2w v): 119 word) ((v2w v'): 119 word)), 119) )
/\  (bitv_binop_inner binop v v' 120 = SOME (w2v ((get_word_binop binop) ((v2w v): 120 word) ((v2w v'): 120 word)), 120) )
/\  (bitv_binop_inner binop v v' 121 = SOME (w2v ((get_word_binop binop) ((v2w v): 121 word) ((v2w v'): 121 word)), 121) )
/\  (bitv_binop_inner binop v v' 122 = SOME (w2v ((get_word_binop binop) ((v2w v): 122 word) ((v2w v'): 122 word)), 122) )
/\  (bitv_binop_inner binop v v' 123 = SOME (w2v ((get_word_binop binop) ((v2w v): 123 word) ((v2w v'): 123 word)), 123) )
/\  (bitv_binop_inner binop v v' 124 = SOME (w2v ((get_word_binop binop) ((v2w v): 124 word) ((v2w v'): 124 word)), 124) )
/\  (bitv_binop_inner binop v v' 125 = SOME (w2v ((get_word_binop binop) ((v2w v): 125 word) ((v2w v'): 125 word)), 125) )
/\  (bitv_binop_inner binop v v' 126 = SOME (w2v ((get_word_binop binop) ((v2w v): 126 word) ((v2w v'): 126 word)), 126) )
/\  (bitv_binop_inner binop v v' 127 = SOME (w2v ((get_word_binop binop) ((v2w v): 127 word) ((v2w v'): 127 word)), 127) )
/\  (bitv_binop_inner binop v v' 128 = SOME (w2v ((get_word_binop binop) ((v2w v): 128 word) ((v2w v'): 128 word)), 128) )
/\  (bitv_binop_inner binop v v' _ = NONE )
`;
val bitv_binop_def = Define `
  bitv_binop binop (v, n) (v', n') =
    if n = n'
    then bitv_binop_inner binop v v' n
    else NONE
`;

Definition bit_eq_def:
 (bit_eq (T, T) = T) /\
 (bit_eq (T, F) = F) /\
 (bit_eq (F, T) = F) /\
 (bit_eq (F, F) = T)
End

Definition word_eq_def:
 (word_eq w1 w2 =
  AND_EL (MAP bit_eq (ZIP(w2v w1, w2v w2))))
End

val get_word_binpred_def = Define `
    (get_word_binpred binop_le = word_ls)
/\  (get_word_binpred binop_ge = word_hs)
/\  (get_word_binpred binop_lt = word_lo)
/\  (get_word_binpred binop_gt = word_hi)
/\  (get_word_binpred binop_neq = (\w1 w2. ~(word_eq w1 w2)))
/\  (get_word_binpred binop_eq = (\w1 w2. word_eq w1 w2))
`;

val bitv_binpred_inner_def = Define `
    (bitv_binpred_inner binpred v v' 1 = SOME (((get_word_binpred binpred) ((v2w v): 1 word) ((v2w v'): 1 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 2 = SOME (((get_word_binpred binpred) ((v2w v): 2 word) ((v2w v'): 2 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 3 = SOME (((get_word_binpred binpred) ((v2w v): 3 word) ((v2w v'): 3 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 4 = SOME (((get_word_binpred binpred) ((v2w v): 4 word) ((v2w v'): 4 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 5 = SOME (((get_word_binpred binpred) ((v2w v): 5 word) ((v2w v'): 5 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 6 = SOME (((get_word_binpred binpred) ((v2w v): 6 word) ((v2w v'): 6 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 7 = SOME (((get_word_binpred binpred) ((v2w v): 7 word) ((v2w v'): 7 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 8 = SOME (((get_word_binpred binpred) ((v2w v): 8 word) ((v2w v'): 8 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 9 = SOME (((get_word_binpred binpred) ((v2w v): 9 word) ((v2w v'): 9 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 10 = SOME (((get_word_binpred binpred) ((v2w v): 10 word) ((v2w v'): 10 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 11 = SOME (((get_word_binpred binpred) ((v2w v): 11 word) ((v2w v'): 11 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 12 = SOME (((get_word_binpred binpred) ((v2w v): 12 word) ((v2w v'): 12 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 13 = SOME (((get_word_binpred binpred) ((v2w v): 13 word) ((v2w v'): 13 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 14 = SOME (((get_word_binpred binpred) ((v2w v): 14 word) ((v2w v'): 14 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 15 = SOME (((get_word_binpred binpred) ((v2w v): 15 word) ((v2w v'): 15 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 16 = SOME (((get_word_binpred binpred) ((v2w v): 16 word) ((v2w v'): 16 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 17 = SOME (((get_word_binpred binpred) ((v2w v): 17 word) ((v2w v'): 17 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 18 = SOME (((get_word_binpred binpred) ((v2w v): 18 word) ((v2w v'): 18 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 19 = SOME (((get_word_binpred binpred) ((v2w v): 19 word) ((v2w v'): 19 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 20 = SOME (((get_word_binpred binpred) ((v2w v): 20 word) ((v2w v'): 20 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 21 = SOME (((get_word_binpred binpred) ((v2w v): 21 word) ((v2w v'): 21 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 22 = SOME (((get_word_binpred binpred) ((v2w v): 22 word) ((v2w v'): 22 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 23 = SOME (((get_word_binpred binpred) ((v2w v): 23 word) ((v2w v'): 23 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 24 = SOME (((get_word_binpred binpred) ((v2w v): 24 word) ((v2w v'): 24 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 25 = SOME (((get_word_binpred binpred) ((v2w v): 25 word) ((v2w v'): 25 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 26 = SOME (((get_word_binpred binpred) ((v2w v): 26 word) ((v2w v'): 26 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 27 = SOME (((get_word_binpred binpred) ((v2w v): 27 word) ((v2w v'): 27 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 28 = SOME (((get_word_binpred binpred) ((v2w v): 28 word) ((v2w v'): 28 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 29 = SOME (((get_word_binpred binpred) ((v2w v): 29 word) ((v2w v'): 29 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 30 = SOME (((get_word_binpred binpred) ((v2w v): 30 word) ((v2w v'): 30 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 31 = SOME (((get_word_binpred binpred) ((v2w v): 31 word) ((v2w v'): 31 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 32 = SOME (((get_word_binpred binpred) ((v2w v): 32 word) ((v2w v'): 32 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 33 = SOME (((get_word_binpred binpred) ((v2w v): 33 word) ((v2w v'): 33 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 34 = SOME (((get_word_binpred binpred) ((v2w v): 34 word) ((v2w v'): 34 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 35 = SOME (((get_word_binpred binpred) ((v2w v): 35 word) ((v2w v'): 35 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 36 = SOME (((get_word_binpred binpred) ((v2w v): 36 word) ((v2w v'): 36 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 37 = SOME (((get_word_binpred binpred) ((v2w v): 37 word) ((v2w v'): 37 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 38 = SOME (((get_word_binpred binpred) ((v2w v): 38 word) ((v2w v'): 38 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 39 = SOME (((get_word_binpred binpred) ((v2w v): 39 word) ((v2w v'): 39 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 40 = SOME (((get_word_binpred binpred) ((v2w v): 40 word) ((v2w v'): 40 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 41 = SOME (((get_word_binpred binpred) ((v2w v): 41 word) ((v2w v'): 41 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 42 = SOME (((get_word_binpred binpred) ((v2w v): 42 word) ((v2w v'): 42 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 43 = SOME (((get_word_binpred binpred) ((v2w v): 43 word) ((v2w v'): 43 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 44 = SOME (((get_word_binpred binpred) ((v2w v): 44 word) ((v2w v'): 44 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 45 = SOME (((get_word_binpred binpred) ((v2w v): 45 word) ((v2w v'): 45 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 46 = SOME (((get_word_binpred binpred) ((v2w v): 46 word) ((v2w v'): 46 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 47 = SOME (((get_word_binpred binpred) ((v2w v): 47 word) ((v2w v'): 47 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 48 = SOME (((get_word_binpred binpred) ((v2w v): 48 word) ((v2w v'): 48 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 49 = SOME (((get_word_binpred binpred) ((v2w v): 49 word) ((v2w v'): 49 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 50 = SOME (((get_word_binpred binpred) ((v2w v): 50 word) ((v2w v'): 50 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 51 = SOME (((get_word_binpred binpred) ((v2w v): 51 word) ((v2w v'): 51 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 52 = SOME (((get_word_binpred binpred) ((v2w v): 52 word) ((v2w v'): 52 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 53 = SOME (((get_word_binpred binpred) ((v2w v): 53 word) ((v2w v'): 53 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 54 = SOME (((get_word_binpred binpred) ((v2w v): 54 word) ((v2w v'): 54 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 55 = SOME (((get_word_binpred binpred) ((v2w v): 55 word) ((v2w v'): 55 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 56 = SOME (((get_word_binpred binpred) ((v2w v): 56 word) ((v2w v'): 56 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 57 = SOME (((get_word_binpred binpred) ((v2w v): 57 word) ((v2w v'): 57 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 58 = SOME (((get_word_binpred binpred) ((v2w v): 58 word) ((v2w v'): 58 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 59 = SOME (((get_word_binpred binpred) ((v2w v): 59 word) ((v2w v'): 59 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 60 = SOME (((get_word_binpred binpred) ((v2w v): 60 word) ((v2w v'): 60 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 61 = SOME (((get_word_binpred binpred) ((v2w v): 61 word) ((v2w v'): 61 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 62 = SOME (((get_word_binpred binpred) ((v2w v): 62 word) ((v2w v'): 62 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 63 = SOME (((get_word_binpred binpred) ((v2w v): 63 word) ((v2w v'): 63 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 64 = SOME (((get_word_binpred binpred) ((v2w v): 64 word) ((v2w v'): 64 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 65 = SOME (((get_word_binpred binpred) ((v2w v): 65 word) ((v2w v'): 65 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 66 = SOME (((get_word_binpred binpred) ((v2w v): 66 word) ((v2w v'): 66 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 67 = SOME (((get_word_binpred binpred) ((v2w v): 67 word) ((v2w v'): 67 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 68 = SOME (((get_word_binpred binpred) ((v2w v): 68 word) ((v2w v'): 68 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 69 = SOME (((get_word_binpred binpred) ((v2w v): 69 word) ((v2w v'): 69 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 70 = SOME (((get_word_binpred binpred) ((v2w v): 70 word) ((v2w v'): 70 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 71 = SOME (((get_word_binpred binpred) ((v2w v): 71 word) ((v2w v'): 71 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 72 = SOME (((get_word_binpred binpred) ((v2w v): 72 word) ((v2w v'): 72 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 73 = SOME (((get_word_binpred binpred) ((v2w v): 73 word) ((v2w v'): 73 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 74 = SOME (((get_word_binpred binpred) ((v2w v): 74 word) ((v2w v'): 74 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 75 = SOME (((get_word_binpred binpred) ((v2w v): 75 word) ((v2w v'): 75 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 76 = SOME (((get_word_binpred binpred) ((v2w v): 76 word) ((v2w v'): 76 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 77 = SOME (((get_word_binpred binpred) ((v2w v): 77 word) ((v2w v'): 77 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 78 = SOME (((get_word_binpred binpred) ((v2w v): 78 word) ((v2w v'): 78 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 79 = SOME (((get_word_binpred binpred) ((v2w v): 79 word) ((v2w v'): 79 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 80 = SOME (((get_word_binpred binpred) ((v2w v): 80 word) ((v2w v'): 80 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 81 = SOME (((get_word_binpred binpred) ((v2w v): 81 word) ((v2w v'): 81 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 82 = SOME (((get_word_binpred binpred) ((v2w v): 82 word) ((v2w v'): 82 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 83 = SOME (((get_word_binpred binpred) ((v2w v): 83 word) ((v2w v'): 83 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 84 = SOME (((get_word_binpred binpred) ((v2w v): 84 word) ((v2w v'): 84 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 85 = SOME (((get_word_binpred binpred) ((v2w v): 85 word) ((v2w v'): 85 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 86 = SOME (((get_word_binpred binpred) ((v2w v): 86 word) ((v2w v'): 86 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 87 = SOME (((get_word_binpred binpred) ((v2w v): 87 word) ((v2w v'): 87 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 88 = SOME (((get_word_binpred binpred) ((v2w v): 88 word) ((v2w v'): 88 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 89 = SOME (((get_word_binpred binpred) ((v2w v): 89 word) ((v2w v'): 89 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 90 = SOME (((get_word_binpred binpred) ((v2w v): 90 word) ((v2w v'): 90 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 91 = SOME (((get_word_binpred binpred) ((v2w v): 91 word) ((v2w v'): 91 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 92 = SOME (((get_word_binpred binpred) ((v2w v): 92 word) ((v2w v'): 92 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 93 = SOME (((get_word_binpred binpred) ((v2w v): 93 word) ((v2w v'): 93 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 94 = SOME (((get_word_binpred binpred) ((v2w v): 94 word) ((v2w v'): 94 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 95 = SOME (((get_word_binpred binpred) ((v2w v): 95 word) ((v2w v'): 95 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 96 = SOME (((get_word_binpred binpred) ((v2w v): 96 word) ((v2w v'): 96 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 97 = SOME (((get_word_binpred binpred) ((v2w v): 97 word) ((v2w v'): 97 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 98 = SOME (((get_word_binpred binpred) ((v2w v): 98 word) ((v2w v'): 98 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 99 = SOME (((get_word_binpred binpred) ((v2w v): 99 word) ((v2w v'): 99 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 100 = SOME (((get_word_binpred binpred) ((v2w v): 100 word) ((v2w v'): 100 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 101 = SOME (((get_word_binpred binpred) ((v2w v): 101 word) ((v2w v'): 101 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 102 = SOME (((get_word_binpred binpred) ((v2w v): 102 word) ((v2w v'): 102 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 103 = SOME (((get_word_binpred binpred) ((v2w v): 103 word) ((v2w v'): 103 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 104 = SOME (((get_word_binpred binpred) ((v2w v): 104 word) ((v2w v'): 104 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 105 = SOME (((get_word_binpred binpred) ((v2w v): 105 word) ((v2w v'): 105 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 106 = SOME (((get_word_binpred binpred) ((v2w v): 106 word) ((v2w v'): 106 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 107 = SOME (((get_word_binpred binpred) ((v2w v): 107 word) ((v2w v'): 107 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 108 = SOME (((get_word_binpred binpred) ((v2w v): 108 word) ((v2w v'): 108 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 109 = SOME (((get_word_binpred binpred) ((v2w v): 109 word) ((v2w v'): 109 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 110 = SOME (((get_word_binpred binpred) ((v2w v): 110 word) ((v2w v'): 110 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 111 = SOME (((get_word_binpred binpred) ((v2w v): 111 word) ((v2w v'): 111 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 112 = SOME (((get_word_binpred binpred) ((v2w v): 112 word) ((v2w v'): 112 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 113 = SOME (((get_word_binpred binpred) ((v2w v): 113 word) ((v2w v'): 113 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 114 = SOME (((get_word_binpred binpred) ((v2w v): 114 word) ((v2w v'): 114 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 115 = SOME (((get_word_binpred binpred) ((v2w v): 115 word) ((v2w v'): 115 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 116 = SOME (((get_word_binpred binpred) ((v2w v): 116 word) ((v2w v'): 116 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 117 = SOME (((get_word_binpred binpred) ((v2w v): 117 word) ((v2w v'): 117 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 118 = SOME (((get_word_binpred binpred) ((v2w v): 118 word) ((v2w v'): 118 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 119 = SOME (((get_word_binpred binpred) ((v2w v): 119 word) ((v2w v'): 119 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 120 = SOME (((get_word_binpred binpred) ((v2w v): 120 word) ((v2w v'): 120 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 121 = SOME (((get_word_binpred binpred) ((v2w v): 121 word) ((v2w v'): 121 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 122 = SOME (((get_word_binpred binpred) ((v2w v): 122 word) ((v2w v'): 122 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 123 = SOME (((get_word_binpred binpred) ((v2w v): 123 word) ((v2w v'): 123 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 124 = SOME (((get_word_binpred binpred) ((v2w v): 124 word) ((v2w v'): 124 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 125 = SOME (((get_word_binpred binpred) ((v2w v): 125 word) ((v2w v'): 125 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 126 = SOME (((get_word_binpred binpred) ((v2w v): 126 word) ((v2w v'): 126 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 127 = SOME (((get_word_binpred binpred) ((v2w v): 127 word) ((v2w v'): 127 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' 128 = SOME (((get_word_binpred binpred) ((v2w v): 128 word) ((v2w v'): 128 word)):boolv) )
/\  (bitv_binpred_inner binpred v v' _ = NONE )
`;
val bitv_binpred_def = Define `
  bitv_binpred binpred (v, n) (v', n') =
    if n = n'
    then bitv_binpred_inner binpred v v' n
    else NONE
`;
val bitv_concat_def = Define `
  bitv_concat (v, (n:num)) (v', n') = (v ++ v', n + n')
`;


val _ = export_theory ();



