name: build

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        polyml: ['v5.7.1', 'v5.9.1']
        hol4: ['trindemossen-1']
        
    env:
      CACHE_DIR: /home/runner/cache
      POLYML_VERSION: ${{ matrix.polyml }}
      HOL4_VERSION: ${{ matrix.hol4 }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.CACHE_DIR }}
          key: os-${{ runner.os }}_polyml-${{ matrix.polyml }}_hol4-${{ matrix.hol4 }}

      - name: Prepare cached dependencies
        timeout-minutes: 35
        run: |
          ./scripts/install.sh && ./scripts/install2.sh
        
      - name: Export Ott files to HOL4 and run Holmake
        run: eval "$(opam env)" && export PATH=$PATH:${{ env.CACHE_DIR }}/hol4_${{ matrix.hol4 }}/bin && make hol
