name: build

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        polyml: ['5.7.1', '5.9.1']
        hol4: ['trindemossen-1']

    env:
      CACHE_DIR: /home/runner/cache
      POLYML_VERSION: ${{ matrix.polyml }}
      HOL4_VERSION: ${{ matrix.hol4 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/work/HOL4P4/HOL4P4/scripts/HOL
          key: os-${{ runner.os }}_polyml-${{ matrix.polyml }}_hol4-${{ matrix.hol4 }}

      - name: Prepare cached dependencies
        timeout-minutes: 45
        run: |
          cd scripts && ./install.sh

      - name: Export Ott files to HOL4 and run Holmake
        run: eval "$(opam env)" && export PATH=$PATH:/home/runner/work/HOL4P4/HOL4P4/scripts/HOL/bin && make hol
